---
title: "1881-08-08:1881-08-14"
subtitle: |
  Reaching Lady Franklin Bay
date: 2024-04-12T03:00
categories: [diary, rice, ice]
editor_options:
  chunk_output_type: console
order: 5
---

## Monday August 8th, 1881

Strong northerly current. New ice formed in the small ponds in the pack at
temp 30° F 1 1/4” in thickness. We are still drifting south — at 11 p.m. off Cape de
Fosse.

## Tuesday August 9th, 1881

Made steam at 12:15 a.m. going north. Made fast to ice again at 1 a.m. At 4
a.m. the ice apparently closing in about us. Were therefore compelled to steam Smith
Sound and get in more open water. 10 a.m. tracking Smith again on account of ice. In
face the ice appears determined to drive us in a more southerly position. It now looks
as if our chances of reaching Discovery Harbor this season are not very good. 11 p.m.
moved west.

## Wednesday, August 10th, 1881

Vessel is still being carried to the south — a strong current from the north has
been perceived. We can now see Franklin Island through the fog. Little by little the
ice is forcing us back. If the main pack should start in a body we would instantly be
carried with it to the S and compelled no doubt to winter at a lower point. After being
so near our destination to be compelled to establish our winter quarters at a lower
Latitude will be a great disappointment.

## Thursday, Aug 11th, 1881

Underway at 3 a.m. Ice ahead appears moving from the west shore. Made fast
to ice again at 4:10 p.m. The ice ahead appears to be moving and ship starts again.
Hope again is to posses some of us — The man in the crows nest reports open water.
As we draw nearer the way appeared open to Discovery Harbour. No ice in sufficient
quantities to offer any obstruction to Lady Franklin Bay. Capes Lieber and Baird
soon passes and at 2 p.m. we were inside the breakwater of Dutch Island. Discovery
Harbro is filled with ice but the stout Proteus can evidently force a passage for
herself. Several hours were spent running with the ice. Each successive charge sending 
her farther into the harbor. As the question of our establishing our quarters
here or nearer the cole-mine four miles distant was not settled, the ship was allowed
to remain quiet until a visit to the coal mine and a knowledge of our prospects should
decide the matter. On entering the the harbor the Boatswain (Mr. White) discovered a
Musk Ox on the side of the hill. Mr. White went ashore, soon a well directed shot
brought him rolling down the cliffs. This started our hunters and after a few hours,
Lt. Lockwood, Clay and Ryan who formed the part, brought back the report that
they had killed 10. Lt. Lockwood and Mr. Clay then started for the coal mine, and on
their way killed 3 more, making 14 muskoxen killed first day. I photographed ship in
ice.

## Friday August 12th, 1881

Lt. Lockwood having brought back information that the harbor near the coal
mine was not accessible and the position for establishing our camp not so favorable as
near Discovery Harbor. Lt. Greely concludes to establish quarters at the latter place.
The ship is then forced through the ice further into the harbor. A difficult task
occupying the time till 2 p.m. She would charge the ice at full speed sending her hull
half it’s length in the ice where she would be sometimes stuck. But extricating
herself would back out and return to the charge. At one time it was necessary to blast
the ice out from under to free her. Preparations are speedily being made for loading
our goods and stores. The cairn left by the English to be examined and their records
read. The cairn is a monument to determination for it is built of hundreds of empty
cans filled with pebbles. I photographed the musk oxen as they lay dead.

## Saturday August 13th, 1881

We were busily engaged today discharging cargo — I gave some assistance to
the Signal Observers in making up their meteorological reports which Lt. Greely
intends sending back by the Proteus.


## Sunday Aug 14th, 1881

From above date till Sunday, August 22nd no important occurrence has taken
place. I have been so busily engaged that it seems impossible to give any time to my
diary. The weather was uniformly pleasant with the exception of Wednesday 18th
when at evening some snow fell. On the eve of the 18th Proteus ready to start as all
cargo was discharged, but the weather being bad, Capt. Pike decided to remain at
anchor until 4 a.m. The majority of party transferred their chattels ashore and erected
tents. I remained on board finishing letters and did not leave the ship until she was
underway.

During the past week I have been making photographs daily at our camp as it
increased in size and the house as it assumed from day to day the appearance of a
human habitation. The negatives are sent to the Signals Office and will serve to show
the progress we are making and also the general appearance of the locality. I was kept
excessively engaged writing my letters up to that time and snatching a few hours
sleep before breakfast. Many letters to write as no other opportunity may be offered
for years. At least one year, and the experience of this season rather shakes my belief
in the ability of a ship to reach this latitude every season. It is a mere chance. I made
most of the negative at midnight,
writing my letters up to that time and snatching a few hours of sleep before breakfast.
The working party has been divided into two groups — one working while the other
slept. In this way the work was going on all the time. Of course night offered no
disadvantages; the sun was above the horizon during the twenty four hours. I was able
to make photographs at any hour of the night.

On the morning of the 19th, 4 a.m. after finishing my letters and making out
dispatch for New York Herald, I went ashore. It was snowing hard. Borrowed a
sleeping bag from Dr. Pavy, and finding that Jewell and Israel occupied a larger tent
than was necessary for their accommodation I was soon comfortably ensconced
inside their tent.

The Proteus did not succeed in getting very far, just outside the breakwater at Bellot
Island. The ice had packed in as firmly to admit of their passing.

On 21st Ryan was taken with an epileptic fit and it was decided to send him home -
this makes the second man sent back for physical disability. Starr, the other man,
showed asthmatic tendencies.
