---
title: "1882-04-02:1882-04-02"
subtitle: |
  Returning for a new sledge runner.
date: 2024-09-02T16:30
categories: [diary, rice]
editor_options:
  chunk_output_type: console
order: 29
---


## Sunday April 2nd 1882

On our way back to snowhouse after our accident last night I told the Dr. that
I could make the trip to home station, Fort Conger, and return on foot in five days and
offered to go. It was the only way out of our difficulty that suggested itself. I thought
a sledge runner could be made for us at short notice and the loss of time, although
considerable, was not so great as to necessarily frustrate our plans for the trip. To give
up after spending so much time and effort would have been a great disappointment. I
sympathized most sincerely with the Dr. to whom the misfortune was greater than to
myself. Dr. Pavy was at first quite averse to my project as it appears to him rather too
hazardous. After discussing the matter for some time I overcame his objections and
desired to start at once—but I will here copy my report which I submitted for his
information when making up his arrival report to the commanding officer after our
return.

In accordance with your request I hereby submit a short statement of the main
features of my uneventful trip to the home Station—to procure sledge runner—while
a member of your northern sledge party in March and April of this year. We, as you
will remember, left Lincoln Bay for the North at 6:30 p.m. April 1st, and the false start
resulting in our misfortune at Cape Union—and our return to the snowhouse, occupy
five and a half hours. Another hour was passed in waiting for the ramekin of tea you
prepared for us making preparation after which —at 10 am., April 2nd I started
accompanied by Jens. We took with us the shoe of our broken runner as I thought it
would expedite the work at Fort Conger. Our outfit was extremely simple consisting
of a small spirit lamp, a small quantity of spirits, and sufficient processed meat and
chocolate for a lunch. We also carried large knives with which to dig ourselves a
burrow in the hard snow should be overtaken by storm or accident before reaching the
first possible stopping place—the snowhouse at Shift Rudder Bay. The thermometer
when we started -42, and the sun was just appearing above the rough icy horizon to
the north pouring a flood of light down the straits and consorting and glistening on
the hummocks and icepoints in our path, in a manner that caused us to lose sight of
the beauty of the scene, in the discomfort experienced in the effect upon our eyes. It
was difficult for us to wear the snow goggles as the condensing moisture obscured
our vision and rendered our step uncertain.

Thinking we could effect a shorter route by foot over the Bay then that
necessarily taken by the loaded sledges we struck across directly for the bold point of
Cape Frederick VII. We soon found ourselves completely beset by snowdrifts and
hummocks and were glad to see the original path as indicated by the marks of the
sledge. We traveled rapidly checking our pace only when an alternative in carrying
the shoe and examined our faces which sometimes required the application of a warm
hand to efface the white seal of Jack Frost. Considerable elation was felt when our
stopping place at Wrangle Bay—representing one days march while outward
hummocks, rubble ice and snowdrifts at the entrance to Wrangle Bay. We sometimes
fell in with the bear tracks and inadvertently following them for a short distance
found the traveling so much improved that we unhesitatingly followed them through
the intricacies of the ice along the ice foot. The advantages of Bruin’s superior
icepilotage partly condoned his offence in eating our pemmican. We began to weary
about the time Cape Beechy was doubled and the remaining four miles, along the
long course of Shift Rudder Bay was made with much difficulty. Jens who before had
always a reassuring smile and shake of the head for answer to my “tired Jens” now
began to answer less confidently and soon replied with a strong affirmative, although
reminded me when his tum for carrying the shoe came. The walking from Cape
Beechy to depot “B” was most tiresome — although smoother— as the frosty, sandy
snow resting on the ice furnished a very unstable foothold for our polished moccasins
at each step slipped back half the stride already too short. Despite our strong desire to
move, our progress, without occasional rest, was not easy to make, and a line of small
decayed hummocks fringing our road- furnished us with resting places. So soon as we
would touch the icy seat I would find myself dozing and would find Jens with his
hand on his heart or lying full length upon the snow fast asleep. When near depot
“B” Jens pushed to stop and rest, but I induced him to move along until within a few
hundred yards of our destination. I then left him lying in the snow and hastened to the
hut intending to look to him so soon as a fire was started. He joined me in about 20
minutes. Doubtless Jens exhaustion was due to the greater exertions and worry he had
undergone in getting the dogs with the broken sledge back to Lincoln Bay for I am
sure that his powers of endurance are greater than mine. We reached the snowhouse
at 2:30 p.m.—altogether traveling 19 hours traveling and covering at least 40 miles.
it is difficult to state exactly the distance traveled as our route was necessarily
serpentine and tortuous through the ice and a long detour had to be made in getting
out of Lincoln Bay

We turned in a sleeping bag after a hasty meal of baked beans which we gave
hardly time to thaw. I intended resuming the march in a few hours—so soon as we
were rested—but did not succeed in waking up until 8 oclock next morning (April 3rd).

Our foot gear we had trusted to the influence of the stove, but found so frozen
we were compelled to return to the sleeping bag and nurse them back to state
sufficiently flexible to admit of putting them on our feet. We started for home Station
at 11 a.m. Attempted several short cuts to shorten the 18 1/2 miles between us and
home, but with the exception of the one across Brenta Bay, found the traveling more
difficult than if we had followed the icefoot. At St. Patrick’s Bay, especially, did we
fare badly. The weather was very (pleasant) compelling us to doff our (tirmiaks) (parkas)
and carry them suspended to our belts. Our sudden and unexpected arrival at Fort Conger causes
some considerable excitement and apprehension for our safety. On reporting to our
Commanding officer he at once ordered the work on sledge runner to commence, and
it was continued up to midnight. We learned that the large North Greenland sledge
party had just departed and I had missed meeting them by cutting across country from
Watercourse Bay, while they followed the coast around Distant Cape.

On Thursday April 4th after another good meal surrounded by the
comparatively luxurious appointments of Fort Conger Jens and I started back to join
you. The sledge runner has completed as Lt. Greely made the arrangement so
advantageous to us that it would follow us to Depot “B” with Lt. Lockwood who was
to start in a few hours with Jewell, Frederick and the dog sledge to join the main
party. We arrived at Depot “B” at 11:30 p.m. after 8 hrs tramp and found the
Greenland party just arrived from Depot “C” Cape Murchison where they had passed
the first night. Lt. Lockwood with dog sledge arrived at 3 a.m. the next morning.

Wednesday April 5th at 3:30 p.m. we bid “goodbye” to the Greenlanders who
had entertained us so kindly, and moved on northward. We carried the runner by
supporting party of its weight allowing the end only to drag. We assumed the burden
alternately and made very good time. The temperature when starting was only -22°,
but the cold increased perceptively although we had no measuring its intensity. We
made a detour that avoided the hummocks and gave us smoother traveling across
Wrangle Bay. Stopped to ascertain the state of cache at North Side and found it
undisturbed. Melted a little ice to quench our thirst and continued around Mount
Parry. It was then midnight. The morning of Thursday, April 6th dawned bright and
clear and we entered Lincoln Bay in a blaze of light. On nearing the snowhouse Jens
was received with more than three cheers by his dogs and a few moments later I was
giving you the latest news from Fort Conger.
