---
title: "1881-11-08:1881-11-14"
subtitle: |
  Fires in the camp.
date: 2024-06-10T22:00
categories: [diary, rice, expeditions]
editor_options:
  chunk_output_type: console
order: 14
---

## Wednesday November 8, 1881

I forgot to state in yesterday’s entry that on our way back we found “Gypsy”
safe and sound. She had increased her progeny to triplets. We wrapped them all in
deer skin and brought them in on the sledge. After arriving at Beechy and while we
were feeding the dogs, one of the pups fell out and before we noticed it, became
partly frozen and afterwards died. Spent comfortable night and started for home 12
a.m. Shortly after we started it began to snow and the track along the icefoot was
difficult to follow. In crossing St. Patrick’s Bay we lost the track. Lt. Kislingbury and
the Dr. considered us as going too far into the Strait, while I contended that we were
already too far up the bay. We found ourselves among hummocks and I left the sledge
and proceeded ahead. I persisted in keeping out in the mouth of the bay and at last
found the old track. We arrived at home station at 7 p.m. Learned that Lt. Lockwood
and party had only arrived a few hours earlier. They found it impossible to cross the
Strait on account of the moving ice in channel and also the soft slushy ice that would
neither bear a foot passenger or allow boat to pass was another impediment. They
started for home from Beechy on the 7th when near the entrance of St. Patrick’s Bay
they found the icefoot overflowed with the exceptionally high tide they had that day.
Most of the party got their feet wet and wanted to go into camp at once. Lt. L.
however advised keeping on till Cape Murchison was reached. As soon as they could
examine their feet several found them badly frozen. Biederbeck was dragged in on the
sledge and will probably loose his great toe.

## Wednesday, Nov 9th, 1881

I have concluded to omit the entry of the daily temperatures until the
comparative readings now being made will furnish us with a correction for the
thermometers. At present the readings are considered slightly incorrect by Lt. Greely.
I will afterwards enter them as -----notes. Today the weather is clearing, with falling
temperatures. No aurora was observed.


## Thursday November 10th, 1881

The parties are engaged for a short time each day in outdoor work. Some
remove the ice forming on the tide gauge; others bank up the house etc. I spent about
an hour each day in hauling ice with Jens and a team of dogs. The ice is for
conversion into water for daily use. An aurora was observed early this morning, also a
faint streamer in the evening. A lunar halo of 22° was seen at 6 p.m.

Considerable excitement over two fires that occurred today. The first was
insignificant occurring in the lean to while Saler was filling lamps. The one caught
fire but was smothered before any damage done. About 4 p.m. Ellison was in the
carpenter tent and attempted the experiment of filling a gasoline lamp without
extinguishing it. He made a very successful failure, but will not likely again try it. In
an instant he was enveloped in flames the whole can of fluid igniting. He rushed out
shouting “Fire!” Our two Babcock extinguishers were brought into (?) and after a
short time the fire was subdued but not before some more tools and clothing was
destroyed. Ellison was badly burned.

## Friday November 11, 1881

Ellison was badly burned. His face and hands are excoriated so that they
appear raw. He presents a sorry appearance. Weather is fair. I hauled four loads of ice
and will continue to do so until the moon leaves us as after that the light will not be
sufficient. Two mock moons were observed from 9:45 to midnight. Weather is
growing colder.


## Saturday November 12th, 1881

Today we experienced the lowest temp so far. Weather clear during the day,
but cloudy at night. It did not affect us very unpleasantly (the cold) and our outdoor
avocations were carried on as usual.


## Sunday November 13th, 1881

Our usual Sabbath varying the routine of the week by its accompanying divine
service in morning and issue of grog at night. The day generally spent in reading and
sleeping. In the evening some hymns and old songs were sung with a strong chorus.
Weather continues to keep fine and clear. Two mock moons appeared at 10:30 p.m.
and passed away at midnight. No auroras were observed.

## Monday November 14th 1881

Lt. Greely commenced work on the pendulum piers in the lean-to today.
Gardiner and Connell assisted him. They succeeded in getting a good foundation laid
using quick plaster of Paris and cement. With the Eskimo and dogs I have hauled my
quota of ice; the tide gauge measured the ice formed in the pool at the (?).
Auroral streamers now observed at noon and continued at intervals during the
afternoon and evening.
Sgt. Israel was engaged in taking magnetic observations which continue for three
days during each month.

