---
title: "1882-03-23:1882-04-01"
subtitle: |
  Setting up depots for others.
date: 2024-08-08T15:45
categories: [diary, rice]
editor_options:
  chunk_output_type: console
order: 28
---


## Thursday March 23rd 1882

We spent a sleepless and uncomfortable night at temperature outside at -40.
We had no effectual way of closing the entrance to the hut and the cold air entered
without difficulty. Dr. cooked breakfast after which we went to the English depot of
rations and overhauled it. It was well snowed over and compelled us to use the shovel
a great deal but was otherwise in good condition. Jewell and his team of dogs with
driver having supported as far as had been arranged started to return to the Station at
12 p.m. He took with him 140 lbs of the canned Australian beef and a small quantity
of each of the following articles: onion paste, curry powder and tobacco. I was much
interested in the manner in which the two Eskimos parted company. They were fully
aware that at least two months would elapse before they would again meet and were
also sensible of the dangers to be passed before that time, yet no word or action
passed between them to show that any unusual feeling was entertained. I vainly
watched for some break in their stoical demeanor. They parted without even a glance
at being exchanged although I know they are sincerely attached to each other. It is
proof of that strange negative character so happily described by the observant Dr.
Hayes.

After Jewell was out of sight we spent the afternoon in picking out of the
depot the stores we intend to use. We also made some improvements in our
snowhouse building a vestibule of snow blocks to add to the warmth. Also made a
walk to pick out the most favorable path for the morrow. At 7 p.m. the thermometer
stood at -39.5.


## Friday March 24th 1882

The sleeping bag occupied by Jens and I was originally intended for one man
—a fat Governor in Greenland. For reducing our constant weights of load to the
minimum before started we concluded that by inserting a wedge shaped extension it
would accommodate two of us and save the trouble of carrying a bag for each. This
furry envelope naturally fell to the lot of Jens and I, the smallest ones of the trio, and
when we tried it at the Station—with lighter clothing on—it appeared large enough.

Our experience in the field however was not exactly as pleasant as we
expected. This part of my journal (as will appear obvious to the most superficial
observer) is written up from notes made from my sledge journal kept while on the
field. I will here transcribe verbatim my entry made on this date: Did not spend a very
pleasant night, sleeping bag too small for two of us and Jens and I have much
difficulty in squeezing into it after which “spooning” we can only turn by concerted
movement. Other movements are impossible. Fortunately Jens is much shorter than |
and our straddled feet reach different depths
in the bag. The door of the snowhouse open with temperatures outside of -56.2
(88 ° below freezing point). Dr. and Jens got up at 4 a.m. I at 5 a.m. I am now at 6
a.m. writing this outside and a glance at thermometer shows the temperature at -45°.
Have been wrestling for some time with my termiak which resembles a coat of sheet
iron and in my frantic efforts to put it on have split it down the back—(imagine the
hieroglyphics in which above entry was made in my diary with pencil held in band
encased in a dogskin mitten as large as a sofa pillow) — to continue later: --

We started north at 8 a.m. with heavy load. “Redeye” one of the dogs being
too big with pups was left behind in the snowhouse to which we will return after
advancing our load some distance up the coast. Temp at start -42°, at 11 a.m. -39. At
noon brisk breeze sprung up from 8. East and had so increased by 5:30 p.m. as to
force us into camp as the traveling was bad and drifting snow prevented us from
seeing the way.

The traveling during the day generally good although we were compelled to
shift from icefoots to straits and back again several times and had to unpack the load
twice and carry it over obstructions. The load was very heavy and when we stopped
dogs appeared tired.


We pitched our tents in a lee of a large hummock in the Straits, about 50 yds
from the icefoot. Dr. cooks supper while Jens and I feed dog and secure tents which
increasing wind endangers. At 6 a.m. temp -36° 1/2. As we were eating our stew and
drinking chocolate, the clouds of condensed vapor condensing and congealing against
the top of the tent, fallen again in a miniature snow storm covering clothes and
sleeping bags in a white sheet while it also falls down our backs and in other ways
aggravates us.

Thrusting my hand in the bag of ice Jens brought in I found the pieces like coals of
fire and withdrew it with the ice sticking as if like butter.

I have two toes suffering from frostbite and the fingers of all three of us are
more or less frost burnt.


## Saturday March 25th 1882

The wind increased during the night and at the usual time for starting it was so
strong that we thought it best to lay over for a few hours. At 12 noon we got up and
after some time in prospecting for a lead out of the labyrinth of ice by which we were
surrounded, we took to the icefoot which in this place is piled up in double serrated
lines as if created at different times. We were compelled to carry the light load with
which we started, piecemeal over about 75 yds. and in places had to cut footholds in
the slippery wall. We left our tent standing with sleeping bags and cooking utensils
intending to return to camp. The wind blew briskly although much moderated, but
fortunately in our backs. We reached Black cape at 8 p.m. Storms still light
and from an (elevated) icy pinnacle we could see a way to the North on the frozen
sea, a low dark streak that so resembled land that had we been the first to gaze in that
direction we should probably make the mistake of the Polaris people who placed
“Presidents Land” where later parties found a sea of ice. It was probably a dark
stratus cloud or some other illusory phenomenon.

We started to return after caching our load and reached the tent at midnight. Temp
when we started -27: while we were away -36, now midnight -32. Milatook was run
over by the sledge but the hardy mutt does not look any the worse for it.


## Sunday March 26th 1882

Temp during night—or morning-- -37° 5. We started back to Lincoln Bay at
10:30 a.m. with a strong breeze blowing and with temp of -33°. We had much
difficulty in keeping our noses from freezing. Poor noses! They are already swollen
and scarified by Jack Frost and our clumsy attempts to protect them with our dogskin
mittens brought the tears to our eyes—how gladly would the Arctic travelers dispense
with this troublesome organ while sledging! We arrived at snowhouse, Lincoln Bay,
at 4:30 p.m. wind had gone down. Temp at 5 p.m. -34.5 “Redeye” ok, but not yet a
mother.


## Monday March 27th 1882

Min temp during night -44: at 10 a.m. when we started back to our tent near
Cape Union (false) it had risen to -23. We had a considerable load but got along
swimmingly. The morning was beautiful calm and clear—“too fine to last” as the Dr.
remarked. About noon a light breeze sprang up from the south and kept steadily
increasing until between 2 and 3 o’clock p.m. It was blowing a gale and we became
anxious to reach the tent for shelter. We also feared it might be blown away before
we could reach it.

The barometer was falling alarmingly fast and the temperature was rising
rapidly—the south gale bringing warm weather.

At 4 p.m. we reached the tent still standing and fortunately sheltered by the
large hummock south of it. The wind was then blowing 30 miles an hour at least and
the temp was only down to -11. but even with this comparatively (warm) temperature
we could never have made the latter part of our days journey if the gale had not been
in our back for the searching wind pierced our forms and the face could not be turned
toward it except for the shortest possible space of time. We had a very unpleasant
time making our arrangements for the night, feeding the dogs, etc. At 6 p.m. temp -
11.5. Wind blowing hard as ever!

## Tuesday March 28th 1882

Spent rather an unpleasant night. The driving snow drifted against the sides of
the tent collapsing it so that our space was curtailed within the limits of comfort. We
were crowded upon each other and forced into cramped positions. The swaying tent
surged and shaken by the gale precipitated upon us the snow formed on the inside
which crept in the mouth of the sleeping bags and made our rest almost impossible.
The dogs outside crowded for warmth and shelter against the tent and at times howled
piteously.
Min temp during the night -25. at 6 a.m. -15; at 7 a.m. -20. at 8 a.m. we started at
Black Cape to add to our cache there. The wind began to moderate at 4 a.m. and
became more to the Eastward. At 11 a.m., it had calmded down entirely and the
weather was as smiling and beautiful as if no storm had ever disturbed the elements.

Our load was heavy and we were stopped repeatedly. At one time we were
compelled to unload and relash the runners which occupied one hour. Temp in sun -5;
in shade -18. Reached Black Cape at 3:30 p.m. Melted some ice, eat a lunch, and start
to return to tent at False Cape Union where we arrive at 8 p.m.—temp: -25.


## Wednesday March 29th 1882

Barometer showed another remarkable fall this morning. Temp (Min) during
night -43. I suffered much with pain in the limbs found on examination swollen to
twice the size of the other. Sleep was impossible. Started with empty sledge for our
snow home at Lincoln Bay to get the last load of provisions and maps, at 10:30 a.m.
and arrived there at 2:30 p.m. Temp at 3p.m. -29. at 7p.m. it had fallen -36.5


## Thursday March 30th 1882

The fall of barometer was followed by what it predicted. Stormy weather this
morning. Wind becoming strong from the south with clouds and drifts of snow. The
minimum temperature during the night was registered was -52 but the southern storm
brought it up to -15 at 12 p.m. A remarkable range!

Traveling was out of the question so we rigged up a (?) lamp to burn cocoanut
stearine which we found in the English depot, and attempted to dry our footgear.

My original entry in sledge journal in evening—outside—is later; later still
blowing and drifting from south with snow falling. My little finger was frozen while
writing this

## Friday March 31st 1882

Having slept part of the day yesterday I did not go to sleep until near morning.
I laid outside the sleeping bag and kept the stearine lamp going. An old number of
Litteil’s furnished me with reading matter. On starting out in the morning I found that
we were completely snowed in — our vestibule full of drift. I found that I could not
ignite the matches which I attributed to dampness and as the only alternative started
for the English depot where we knew there were several boxes of dry ones. Had much
difficulty in effecting an exit. Fortunately we had a shovel within and with it I dug my
way and seeing daylight through the snowy shell forced my head and shoulder
through it to the open air. While doing so I found breathing difficult and several times
while shoveling I felt faint and almost unable to continue. This showed us that it was
foul and nephitic air, and that it was due to this the matches would not burn.

The storm had ceased and only the drifts showed the effects of yesterdays
storm. At 8:30 a.m. with a light load (396 lbs. of the English canned meat) we started
for our tent at False Cape Union intending to return at once to our depot at Lincoln
Bay for the last of our provisions which were rather heavy to add and carry in our
load. Reached tent at 12:40 p.m. Started to return at 1 p.m., arrived at Lincoln again at

Temp at 4 p.m.-27.5 Bar. 30.39


## Saturday April 1st 1882

As the season is now advanced so that the influence of the sun can be felt
considerably. Dr. thinks it best to change our time of travel from day to night so that
we may profit by the suns warmth while sleeping and also because the reflection of
the night light an (?) unpleasant effect upon the eyes is not so great. We therefore
decide to lay over till evening and then start (?) but rise early.

Minimum temp during the night -35.0 at 12 p.m. -30, at 4 p.m. 38.8

Dogs irrigated my satchel last night so completely I did not like to handle my sledge
journal which it contained. It was lying on the sledge and being black and glazed
attracted Kingatook’s attention, the other dogs faithfully following his example. We
started north at 6:30 p.m. not expecting to again visit the snowhouse (Lincoln Bay)
until our return homeward. Took “Redeye” along she has not had her pups and her
procrastination makes it appear that she is a malingerer taking advantage of the fact
that she is invalided. She looks as if she were about to present us with a full grown
team of dogs, harnesses and all.

Getting along swimmingly and even congratulating ourselves on the fact that
our work would now be on new ground in a few days, when —in passing from the ice
foot to the Straits at Cape Union (a place safely passed frequently by us) the sledge
bounded awkwardly from the icefoot so that on a lower level and split one runner.
Our consternation was indescribable. It appeared broken beyond al! hope of repait
and the Dr. was completely prostrate. When unloaded and dragged slowly back to the
snowhouse carrying nothing but sleeping bags and cooking gear. The sledge pulled in
its broken state, awkwardly and slowly. Reached snowhouse at about midnight
