---
title: "1882-04-06:1882-04-10"
subtitle: |
  Getting to Black Cape and Cape Rauson in a windstorm.
date: 2024-09-02T17:00
categories: [diary, rice]
editor_options:
  chunk_output_type: console
order: 30
---


## Thursday April 6th, 1882

When we reached Lincoln Bay it was 6 a.m. We had made the distance,
including stop at Wrangle Bay in 15 hours. The Dr. set to work to prepare us a meal
and Jens and I turned in. Meanwhile, the former had his own experience to relate,
Left without a watch he used the bold point of Cape Frederick VII for a sundial and
was able to inform us of the day and almost the hour. The dogs kept him company
and we found “Redeye” installed in the corner of the igloo with one little puppy. It
appears that both “Redeye” and Milatook added to the canine population of Grinnell
Land, but of both families all but one little chubby spotted fellow disappeared down
the capricious jaws of their fathers. The survivor then became a bone of contention to
the bereaved mothers and our son of Galen did not know to which it should be
awarded. Under the impression that “Redeye” had lost the greatest number he decided
in her favor. It is unnecessary to state that the Dr. understood the allusion when he is
addressed as Solomon — Poor Red did not enjoy the maternal office long for
Kingatook (to use Jens term) “scoffed” the tender scion of caninity.

At 7 p.m. we again abandoned our snowhouse and started north. For several
succeeding days (see sledge diary) we were engaged in hauling our stores from Cape
Union to Black Cape. The traveling was very difficult; the icefoot inclining at a sharp
angle from the cliffs to the sea and presenting an inclined plane along which the dogs
crawled—the sledge following on only one runner most of the time and always in
imminent danger of toppling over. The surface of the road was glazed by the sun and
so slippery that at times the whole caravan—dogs, sledge and men—would slide
swiftly from the foot of the cliffs to the line of paleocrystic bergs below, among
which we floundered. At other times the faithful dogs would succeed in maintaining
their hold by inserting their sharp claws in the crust but the sledge and we with it
would describe the section of a circle with the dogs for a center and their traces as a
radii. When the pressed up ice in the foot disrupted our passage we would take to the
Straits but the traveling there was as if and immense inverted harrow. Our watch
stopped on the 7th and set by guess. On the 8th and 9th it blew a gale part of the time,
on the latter day when at Black Cape compelling us to take down tent and build
snowhouse. Temperature warmer (see sledge diary).



## Monday April 10th 1882

At Black Cape. Wind blew so hard that a little after midnight the tent was
blown from its ropes and we had to fold it up at 4 am. It abated a little and
encouraged us to start although still strong enough to almost take us off our feet. At 5
a.m. we were over the icefront on the Straits -Temp 0. Wind began to increase. In
smooth places propelling the sledge in an alarming manner (wind was in our backs)
and crowding on the poor dogs who were leaving the marks of their nails on the ice in
their desperate effort to keep from being blown away. One of us and the driver would
support himself by the upstands of the sledge and the other was frequently seen to
throw himself prone upon the ice to prevent being dashed along and hurled against
the blocks of ice.

At 10 a.m. we reached Cape Rauson near Alert’s winter q’rt’s and found we
could proceed no further as the gale was increasing and the dogs could not be
managed. The icefoot here placed us 50 ft above the sea level, and we could not trust
ourselves in the high icy pinnacles without fear of being blown off. Wrapping our
sleeping bags under the lee of a hummock we crawled in, munching some hard bread
to satisfy our hunger. The dogs curled themselves up for a nap, and here we remained
all through the day and the night, the snow drifting in the sleeping bags about our
faces despite all our precautions with the flaps, so great was the force of the searching
wind even in a sheltered place. At times during the night we would get up for
observations and to relieve our bodies from the cramped positions in the sleeping
bags but at no time was it possible to make a start. It was almost impossible to stand
upright and locomotion was out of the question without holding onto ice and rocks.
At this place, Cape Rauson, we found a can of pemmican left by the English. It was
indicated by a small cairn of rocks which first attracted our attention. Cairn contained
32 lbs and we found it excellent eating even without cooking. In my sledge journal of
this date I find I have complimented the fortitude and patience of our faithful team of
dogs. Even now I can think of nothing connected with our trip that so stirs my breast
with kindly emotion as the remembrance of fine animals struggling day after day
through ice and snow, piercing winds and blinding drifts, dragging heavy loads over
rough rugged roads with their feet sometimes cut and bleeding from the icy chrystals.
