---
title: "1882-02-01:1882-02-08"
subtitle: |
  Extreme cold.
date: 2024-06-22T20:30
categories: [diary, rice]
editor_options:
  chunk_output_type: console
order: 23
---

## Wednesday February 1st 1882

Remarkable mock moons observed today. Connell’s birthday. He “does not
care to celebrate it.” Says he has not any reason to show any appreciation of the
chance of his birth. Lt. G in evening favored us with a few cool remarks on ice.
Temp Min -51.0 Max -46.2 , Mean 49.07

## Thursday February 2nd 1882

I hauled ice as usual. Pup is beginning to work very well in harness. The light
has so increased that I could see to read a newspaper out of doors. Temperature still
very low.

Min -56.5 Max -45.5., Mean 51.59



## Friday February 3rd 1882

Nothing noteworthy occurs today. See private diary for account of a
circumstance not worth recording here.

Min -62.1 Max 43.3., Mean 48.75

Note without stating it— I wish it understood that_all these figures represent the
temperatures observed and corrected.


## Saturday February 4th 1882

This morning while I was hauling ice with Jens and the dog team the
temperature was as low as -60 on the ice floe. This temperature — strange to say—is
not difficult to stand for a few hours while exercising violently. Of course it required
much care to preserve nose and cheeks from freezing.

Max -43.3 Min -54.6 Mean -47. 85

## Sunday February 5th 1882

Israel spent two hours in the observatory today. The pursuit of the science of
astronomy under the circumstances rather cools the ardor of the youthful observer.
Our usual Sabbath occurrences, Rum and Psalms singing in the evening. The
observer off duty finds it difficult to sleep. Temp. Max -45.1, Min -54.1, Mean 51.37


## Monday February 6th 1882

A very cold day. The temperature was below -50 all day. I went to Dutch
Island and found the lantern abandoned by Whistler at the time of misadventure after
Jens. Temperatures Max -50. Min. -57, Mean 53.65.


## Tuesday February 7th 1882

Nothing worth recording except the terrible low temperatures. Temperature
Max -51.4 Min -58.6., Mean 55.41


## Wednesday February 8th 1882

Brainard and I walked to Dutch Island. It required great vigilance to prevent
our faces from freezing. The cider issued this evening so sour that its use was
discontinued by the most of us. Max. 45.5 Min 55.9 Mean 50.99
