---
title: "1881-11-23:1881-11-30"
subtitle: |
  Thanksgiving and auroras.
date: 2024-06-12T21:00
categories: [diary, rice, thanksgiving]
editor_options:
  chunk_output_type: console
order: 16
---

## Wednesday November 23rd 1881

Brainard and Cross were experimented this morning on the feasibility of
lighting a short rifle range artificially for the use of the marksmen in the coming
Thanksgiving. They found that at 25 yds good light could be thrown on a target and
also sufficient for sighting the gun.

The pendulum piers are now sufficiently high; and the erection of an ice house
over them was commenced today. Weather clear, an aurora was observed at 9 a.m. It
disappeared in short time; was of ribbon formation.The cooks are making great
preparations for tomorrow’s dinner with the exception of the regulation turkey the
menu is of the real Thanksgiving flavor.

## Thursday, November 24th 1881

The day clear and favorable for the sports to be engaged in. Of course the
drawbacks of darkness and cold must be taken into consideration. We are
unfortunately in the dark period of the moon the presence of which would supply us
with all the light we would require. Thermometer over 60 below the freezing point
making this doubtless the coldest Thanksgiving day that has ever been celebrated.

At an early hour the men were all engaged in perfecting their arrangements for
the different races; the cooks preparing their (hands?) and even the dogs making
noisy demonstrations as if to show that they too entered into the spirit of the day.

After breakfast the first thing on the programme was the snowshoe race. It
was called for 10 am: but for an hour before that time the clattering of the shoes could
be heard through the quarters as the men tested the security of the fastenings. We all
repaired to the course on the ice in harbor which was staked out and very imperfectly
lighted. The distance was 200 yds and return. Eight competitors entered and a good
start was effected. And now the affair became most amusing to the bystanders. Many
of the men were not familiar with the cumbersome footgear and this added to the
difficulty of finding the way over the ill light course, made their progress most
awkward and erratic. The “Montreal Snowshoe Club” would have considered it a
strange exhibition. An unperceived piece of ice would trip some luckless fellow up
and away he would go floundering in the snow to serve as a footmat 
for his impetuous rivals who were following him with more haste than speed.

As soon as the unfortunate could recover his 2 x 4 feet he would probably be run into
by some fleet footed Mercury who could not distinguish him from the surrounding
snow in which he had been wallowing. Many were the mishaps before the goal was
reached.

Sgts. Brainard, Ralston, Gardiner came in and won the first three prizes. They
reached the home stake in the order in which they are named.

Prizes were:
1st Bot of pres. Peaches: 1 gill rum, (towel) and soap.
2nd 1 gill rum, towel and soap


We then repaired to the quarters where bets were settled and paid and other
wagers laid on the result of the approaching running race. I found myself the winner
of a large amount of tobacco (our legal tender) having backed Brainard against
Gardiner, who was the favorite.

I acted as stakeholder for the party and in that capacity handed over a large
amount of tobacco to the lucky gamblers.

The running race footrace now came up and after a tie between three of the six
contestants it was soon over and the first place won by Ellis, Henry second and Linn
third. Prizes; 1st 1 pt. rum, towel and soap, 2nd 1 gill rum and towel, 3rd 1/2 gill and
soap.

The rifle shooting came last and most of the party engaged in it. Henry won
the first prize (bot of pres. peaches, 1/2 pt rum and soap), Jens 2nd (1 gill rum, towel
and soap) and Cross 3rd 1/2 gill rum and soap. (over)
We were much interested in the result of the dog driving match between the two
Esquimaux. They were made to understand it perfectly i.e. the arrangement, and set
about harnessing up the dogs. While they were doing so we went inside the quarters
expecting to be notified when they were in readiness so that we might see and
regulate the start. However the canine Jehus took the matter in their own hands. We
discovered they had gone and patiently awaited their return. They came in shortly at a
terrific pace Frederick ahead thus winning the pipe and half pound of tobacco
constituting the prize.

Three auroral streamers were observed.

We were now ready for dinner which was served at 4 o’clock. I give here the
bill of fare which considering our distance from market was varied and palatable.

Our chef de cuisine excelled himself:

(Oyster soup, crabs, lobster salad, Eider Ducks, boiled ham, green corn, lima beans,
asparagus, jelly cake, fruit and sponge cakes, Peach pie, blueberry pie, vanilla ice
cream, coffee, warm biscuit, nuts figs etc.) After dinner grog was issued larger
quantity than usual and songs were in order.

Lt. Greely having appointed me distributor of the prizes I attached the said
role of each of the party and succeeded in getting up a most ridiculous dress suit for
the occasion: an old long tailed coat of Jewell’s was transformed by the use of shears
into a swallow tail of remarkable pattern, a dilapidated white vest, immense collar,
profuse jewelry manufactured by the tinsmith, and an immense pair of Esquimaux
boots completed the costume. Lt. Greely made us a short address after which I
conferred the prizes.

## Friday November 25th 1881

In chronicling our celebration of yesterday I lost sight of the fact that the first
number of our paper was issued yesterday. It made a very good appearance and we
the editors, thought it interesting. It was little appreciated however, by the majority of
the party. Henry’s department was the personal column and some of his lists although
perfectly harmless gave great offense to those who were alluded to. The bully
Whistler as usual made a complete ass of himself. Frederick also considered himself
greatly aggrieved. Although contributions had been solicited there was no response
except from Lt. Greely who sent in a short letter over “Occasional.” For my part of
the sheet see “Arctic Moon” of date Nov 24" editorial Arctic Moon account of Lt. K’s
kindness to dogs Wrangle Bay trip, (?) from the Esquimaux, etc. Lt. Lockwood
furnished the preamble and heroic account of and adventure of Lt. Kislingbury and
Dr Pavy. 

An Auroral arch was observed at 6:45 and other at 9:55 a.m. The latter was the most
beautiful, exceedingly bright and of a delicate pale yellow color. Weather clear.
Temperature low.

## Saturday, November 26th 1881

Weather clear. An observation of the temperature of the sea was taken today
with the following result. Temp at surface 28°0. Thickness of ice 29”


## Sunday November 27th 1881

Temperature low. Cross while taking a walk had his ear frozen. Lt.
Kislingbury and I walked to Dutch Island as a constitutional. Notwithstanding the
exercise of great care on my part I froze one of my cheeks.

At 10 a.m. an auroral streamer was seen.

The laugh is decided against Sgt. Brainard today. He started with two or three
companions to walk to Dutch Island, which by the way, is the objective point of all
pedestrians, the intervening path being well beaten, and was not aware that the two
Eskimos had preceded him. It is very dark now and they had proceeded but half way
when by the dim light they saw what they supposed to be a pack of ravenous wolves
emerging from the ice hummocks and making for them. They were unarmed but
Brainard with great coolness told his companions to get their knives in readiness and
prepared to repel the onslaught of the ferocious beasts. Hastily opening their knives
some of them insignificant pen knives they stood in an agony of suspense until the
near approach of the animals proved them to be
dogs that had accompanied the Eskimos and had started on in advance to meet the
new party with demonstrations of delight and no belligerent intention whatever.


## Monday Nov 28th, 1881

Several appearances of auroral light were observed today. Temperature low. I
hauled six loads of ice with the Eskimos and dog team. This furnished me with an
amount of exercise which is beneficial, but arduous. I find the dogs more interesting
than one would suppose. They exhibit remarkable sagacity and intelligence. Nothing,
however, can overcome their propensities for fighting. During the couple of hours I
was engaged with them I noticed nine different encounters which were usually
general, no non-combatants to be seen.

They have divided into two parties and it does not appear possible to associate
one party with the other. I was only using one team and the other apparently jealous
of the preference shown the first barred the road at every point where it was possible
and contended the passage of the loaded sledge. I was compelled to precede the team
and drive them off. Lunar halo and mock moons were seen at 3:30 p.m. They
presented a beautiful appearance.

## Tuesday Nov 29th 1881

I hauled ice as usual in the morning. Jewell being ill I took the observations
from 4 p.m. until midnight. New aurora observed. Weather clear all day- lowest temp
observed -37.5° F.


## Wednesday November 30th, 1881

During the day the temperature fell to -43°. The Mercury froze at -37°.9.
While taking the 3 p.m. observation Gardiner while on his way to the tidal gauge fell
and fractured his leg above the ankle. I finished his tour and will take his place at
midnight. Being desirous of completing my knowledge of German and Biederbeck
wishing to improve his English we have made an arrangement by which we shall
interchange instructions in our mother tongues. We had our first lesson this evening.

