---
title: "1882-03-08:1882-03-14"
subtitle: |
  Preparing for a Greenland trip.
date: 2024-08-08T15:30
categories: [diary, rice]
editor_options:
  chunk_output_type: console
order: 26
---


## Wednesday March 8th 1882

The subject of gas was agitated considerably today. The effects of the gas
evolved from our stove has become a matter of grave importance. There are few of us
who have not felt the pernicious effects of it—spending so much time indoors as we
are compelled to do—and it is time some change was made in the stove’s pipe to
prevent it. Temp. Max: -32.2, Min: -37.6, Mean: -34.27


## Thursday March 9th 1882

Lt. Greely sent me with Connell and Biederbeck to Lake Alexander (actually
Alexandra) to ascertain the thickness of the ice there. Ralston accompanied us as far
as Mt. Ovibus which he ascended to get a view to the N.W. towards United States
Range. We had a cold time of it; were 9 hours gone and had our noses frozen
repeatedly. We were several hours getting through the ice which we found to be 80
inches in thickness.

We were compelled to commence with a large hole at the surface so that there would
be room to work when the hole deepened. At last the digger found the ice above his
head on all sides. We found that Dr. Pavy and Linn had
retumed from the Greenland side having deposited their provisions in Gap Valley.

Linn gave me an instance of Jens toughness: Linn, after one of the hardest
days work traveling through a storm was so completely tired out that he at once
crawled in the double sleeping bag and fell asleep. Jens, after attending to the dogs,
came in the tent to sleep but supposing Linn to be ill, laid outside the bag all night. He
must have spent a terrible night as the temperature was below -40!

Crazy Jane,—one of the dogs, called Milatook by the drivers, — amused us
very much with her antics when a seal skin shoe was placed on her sore foot. She had
the most ludicrous manner of holding it up and inspecting it. Lt. Greely made the
ascent of Cairn Hill. Henry complains of rheumatic pain and Israel takes his place on
observations.

Max: -26.1, Min: -36.6. Mean: -31.7


## Friday March 10th 1882

Bean dryer to work all day. Weather comparatively warm. I walked down
with Dr. and we talk over plan for his northern trip. Linn’s experience with canvas
boots does not encourage us much to believe in their suitability.

Temp Max: -18.8 Min: 29.7 Mean: -23.05


## Saturday March 11th 1882

I was testing some thread for Lt. G to see if it could support sufficient weight
to allow it to be used for deep sea sounding.

Israel and I took sea temperatures and measured thickness of ice in harbor.
Max: -10.7 , Min: -18.9. Mean:-13.19

## Sunday March 12th 1882

I went to Distant Cape and from there proceeding some distance on the ice to
ascertain if it was fit to travel on in the direction of Polaris Bay. Connell accompanied
me. Found the walking very bad and did not proceed further than 2 or 3 miles in the
Strait. The traveling across from Distant Cape to Thank God Harbor is almost
impracticable. I should advise a person crossing to start at Cape Murchison as the
floes appear to be larger and less hummocky. We found the hummocks closely
packed and soft snow dumped between. A strong breeze sprang up as we started to
return. Lifting the snow in blinding sheets. Fortunately it was in our backs: it would
have been impossible to proceed to the fort had it been in our faces. We arrived at the
Station badly frozen up: faces coated with frozen snow and temiaks as stiff as sheet
iron.

In the evening Lt. Greely had some conversation with almost all the members
of the party, eliciting their wishes or willingness to go on the arduous sledge trips. To
the credit of all it must be said that great enthusiasm was shown; everyone quite
anxious to take part in the exciting if dangerous and arduous work. The commanding
officer asked me to take some photographs of the party before we start out. The Dr.
and I will start on 18th of this month. Later Lt. G interviewed me in regard to my
correspondence to NY Herald—see private journal.

Max: -8.9, Min: 29.8, Mean: 21.31

## Monday March 13th 1882

Everyone is busy today preparing the party to start for Greenland side with
boat and provisions; the boat to remain as a safeguard for the later party to return in
case the Straits are broken or open. Brainard, Biederbeck, Schneider, Elison Connell, 
Whistler and Linn will compose the party. They will gone seven days at least. I made
some negatives of the launch and ice foot. But in developing I found that the light
was still too weak.

Max: 29.9 Min: 36.6 Mean: 34.94


## Tuesday March 14th 1882

The party mentioned above started today. I accompanied them to Distant Cape
with Eskimo and dog sledge carrying part of their load. They all started off in good
spirits. I was much amused by Whistler’s request for fifteen leisure before starting to
commune with his photograph of some frontier inamorata of his whom he designated
as “Broncho Moll”. —see private journal.

My Eskimo Jens brought me back at a terrific rate using the 20 foot leash to
great advantage. Rushing through the cold air was like facing a biting breeze and in
spite of all my efforts I froze both cheeks. I found that the temperature had fallen ten
degrees while I was gone! Max: -35.3 Min: -45.3 Mean: 38.08
