---
title: "1881-07-17:1881-07-20"
subtitle: |
  Sending mail.
date: 2024-03-02
categories: [diary, rice, greenland]
editor_options:
  chunk_output_type: console
bibliography: refs.bib
---

## 1881-07-17

This morning we are informed that a boat leaves here for Egadesminda, where a Danish ship is lying about ready to start for Copenhagen and will carry our mail matter, which can be sent to the United States, via Denmark.
We are all therefore busily engaged in writing to friends and relatives.
I send communication to the New York Herald, reporting our arrival and stating our chances for getting through to Lady Franklin Bay, as well as we can judge from the outlook here.
The day is a very fine one. 
The bell in the primitive little mission church is calling the little community to worship.
Some of the men attend.
Snyder volunteers his services as organist to the small instrument which stands in one corner of the church.
After the services is over he pleases the Esquimaux very much by playing them some lively music, soon attracting a much larger congregation than had attended the worship.
His music, which was interspersed with an occasional jib and dancing tune, was rather too secular to be appropriate for the Sabbath, but we are compelled to admit that the natives were more pleased with it than with the preceding devotional exercises. 
I meet the same faces I saw here last year.
Mr. Smith is still Inspector; Governor Fliescher is Trader, and there has been no material change in teh Esquimaux population.
The are all pleased with our ship which they consider "Much Strong."

## 1881-07-18

It is difficult for one not noting the time to distinguish night and day here.
The sun does not set till about 11 p.m., and is up again at 1 a.m.
The evening and morning twilight blend into one, casting a silvery, misty light over everything.
I am writing this in the cabin at midnight, without the aid of artificial lights.
The crew have been busy all day, shifting the cargo and putting more coal in the bunkers.
Our men are bringing off the lumber that was left by the Gulnare, also the pemmican stores, etc.
It has been too foggy for me to make photographs of Disco or the ship.
On the day we arrived here we noticed a magnificent iceberg near the mouth of the harbor.
It was in the form of an immense arch, and presented a very impressive appearance.
It was my intention to return and photograph it at the first opportunity, but we had barely reached an anchorage before it fell to pieces, with a terrific crash louder than thunder.
The sea was disturbed for miles.

## 1881-07-19

I make several negatives today; photograph the Proteus and Godhaven Harbor.
I also make a group of the Governor's family and Miss Smith and her governess.
They are very much pleased to have the opportunity of being photographed, and dress themselves for the occasion with great care.
Miss Smith and her companion look particularly charming in teh bight lively colors of the Danish peasant girl.
At least, they appeared very charming to us, who do not expect to see another woman in a civilized costume for two years.

Lieut Greely has purchased a quantity of white whale skin for food.
It is an excellent antiscorbutic, and is said to resemble tripe in flavor.
It is in a dried stated.
He also has contracted for dried fish and walrus meat, which is to be the food of the dogs.
We will take in about fourteen dogs here and will get others at Rittentank and Upernavik.
Inspector Smith and Governor Fliescher are aiding our commander in every possible way.

## 1881-07-20

Took aboard fourting dogs, with dog food for their consumption.
The walrus meat is most disagreeable in odor, as it is partially decomposed, but appears to be relished by the dogs.
Getting the animals on board was an exciting operation.
They offered every resistance and howled and yelped in a most discordant and disagreeable manner.
They are now penned in a small space on deck where they snarl and snap at one another in a most unfriendly way.
Several encounters between the more warlike of the males have settled the question of supremacy, and now one battle-scarred old veteran struts around, master of the situation.

Dr. Perry arrived from Rittentank today, looking well.
He reports H. Clay still in Rittentank in good health.
