---
title: "1881-11-15:1881-11-22"
subtitle: |
  Planning a camp newspaper.
date: 2024-06-12T21:00
categories: [diary, rice, newspaper]
editor_options:
  chunk_output_type: console
order: 15
---

## Tuesday November 15th 1881

The weather’s still cold. Several acids and oils were placed in the instrument
shelter to determine the relative freezing point. They all became much denser in a
short time. Coal oil assumed the consistency of syrup.

Light snow 3:45 p.m. to 11 p.m.

“Lt. Greely today issued order No 9 to the effect that Thursday Nov 24 will be set
apart as a day of Thanksgiving corresponding with the day observed as a holiday in
the United States. It is proposed that we shall make it a holiday and engage in races
rifle matches and other amusements. The commanding officer offers prizes to
contestants in the different matches.

## Wednesday Nov 16th, 1881

The moon left us today. Lt. Greely and two men engaged on the pendulum
piers. Others hauling work ----in addition to the usual routine of outdoor work. Lt
Lockwood, Henry and I have decided to start a paper which is to be called the “Arctic
Moon” and will appear bi-monthly. We issued a prospectus today informing the party
of our intentions and soliciting contributions and subscribers.


## Thursday November 17, 1881

I hauled some ice this morning, although the moon has disappeared there is
significant light to work by. Lt. Lockwood with two men was engaged in finishing the
ice house in the harbor which was commenced some time ago. It is proposed to use it
as a shelter for a self-registering tide gauge.

In laying the foundation of pendulum piers the temperature of the earth at a
depth of 18 inches was found to be 7°.0, the temp of air — 5.0. This is in the shed or
lean-to adjoining officers quarters.


## Friday November 18th 1881

The programme for Thanksgiving was arranged today. The
amusements will consist of a snow-shoe race, foot race, shooting race, and most
interesting of all, a dog race between two teams in harness to sledges. Jens and
Frederick the Esquimaux will be the drivers. A grand dinner will be prepared.


## Saturday Nov 19th, 1881

It was decided to have a thorough cleaning out of the quarters today. As the
building was inhabited while the work was going on I took a walk to Dutch Island
with Lt. Kislingbury. When we returned everything looked much brighter, cleaner
and more cheerful. The weather continues clear and comparatively, not very cold.”


## Sunday November 20th, 1881

Lt. Greely read to us a chapter from the Bible as usual and which, most of us
took a constitutional walk. In the evening Schneider’s violin and I furnished
instrumental music as an accompaniment to the vocalists engaged in rendering some
ancient hymns and songs. Weather clear.


## Monday November 21st, 1881

A clear day. Lt. Lockwood completed his ice house. The race course was
prepared by removing snow and placing stakes. The course is on the ice in harbor,
near the shore. The distance for snowshoe race will be 200 yards and return; foot race
100 yards straight away. The sledge race will be from Station to Dutch Island, a
distance of two miles, and return.

## Tuesday November 22, 1881

Lt. Lockwood, Henry and I were busy preparing our paper for press. It is to be
issued on Thursday. It appears that we shall have to depend on ourselves for original
matter as no contributors to our columns have made themselves known.

House was banked with snow at some exposed parts. Weather clear. A very brilliant
meteor fell at 10:30 p.m. from Zenith to horizon. No tail. Color blue.
