---
title: "1881-07-07:1881-07-16"
subtitle: |
  Leaving Newfoundland
date: 2024-04-10T02:00
categories: [diary, rice, greenland]
editor_options:
  chunk_output_type: console
order: 1
---

## July 7th, 1881 St. John’s NF

This morning the freight for the expedition that arrived per Hibernia was
brought on board the Proteus and every preparation was made for a start — at noon,
Capt. Pike gave the orders to “get under way” — at about 12:30 we move from our
anchorage and amid cheers and the waving of handkerchiefs from the shore, steam
slowly through the narrows. Considerable interest is taken in our departure and it is
with feelings of regret we gaze for the last time for many days upon that most
interesting picture of society and civilized life represented by a group of gaily dressed
ladies who stand on Signal Hill and kindly waved us good by.

Bleak and cold as Newfoundland is with its draping of fog hanging over it’s
high cliffs. We shall exchange it for that desolate land of eternal snow with regret.
Our start is a favorable one as we go coasting along the cold shore
under full sail and steam at a splendid rate. The wind is a pleasant land breeze and
we are carried by the entrance to the great bays Conception and trinity. The ships
crew are busily engaged cleaning up the decks and putting things in their proper
places — “Making things shipshape” as the man says. Our party occupy their time
locating & doffing their city costumes and donning clothes more substantial and
better adapted to ship life. Some are evidently meditating on the future of our arduous
undertaking towards which we have taken our initial step today and which has
probably, in many cases, never been so seriously considered as of this moment.

To realize we have left behind us relatives, friends, society civilization and
everything that makes life pleasant on this terrestrial sphere, for the long space of two
years is enough to furnish ample food for reflection
even to the most thoughtless. And thus it is impossible to avoid looking forwards
with something like apprehension to the future sojourn in those regions of perpetual
snow and ice under a hostile sky. No matter how much forethought may be exercised
these thoughts have never so strongly suggested themselves as at this time when we
find ourselves in the North Atlantic with our ship prow pointed to the North Star and
every revolution of the propeller speeding us nearer our inhospitable destination and
farther from home and friends. We retire at a late hour to be lulled to sleep by the
motion of the ship which has not yet become unpleasant and dream of icebergs and
polar bears.

## July 8, 1881

We are fording along at a splendid rate. The weather is fair but the
temperature is growing much cooler. Now that we are all together a roll call to make
acquaintance (?). We are members of an Arctic exploring expedition sent out under
the auspices of the War Department United States of America. (or more immediately
of the Chief Signal Office USA.) for scientific observation in the Arctic regions[^firstinternationalpolaryear]. The
plan of the expedition is to establish a station at Lady Franklin Bay. Lat 81° 40’ N and
spend two years in observation and exploration making sledge journey to the North at
such times and season as practicable and formable. The expedition is under the
command of Lieutenant A.W. Greely and the following are various of the persons
accompanying the party.

* Lieut. A. W. Greely — in command
* Lockwood
* Kislingbury
* Israel — Astronomer
* Gardiner
* Jewell — Meteorologist
* Ralston
* Rice — Photographer

## July 8, 1881

For our transportation to Lady Franklin Bay the United States Govt. has
chartered the sailing steamer Proteus and are sailing from St. Johns, Newfoundland.
She is commanded by Capt. Pike who has for his First Officer Mr. Norman, Second, .
Mr. White, Mr. McPherson is First Engineer and Mr. Carmichael Second. The crew
is composed of sturdy Newfoundland sailors — Capt. Pike and his mate have all had
long experience in ice navigation and our ship is especially adapted for her mission as
she was built for the seal fishing and everything that experience could suggest was
done to make her capable of resisting the action of the ice.

## July 9th, 1881

There is a strong wind from the NW which makes our progress very slow —
The temperature is getting much cooler. We only make about 5 knots today.


## July 10th, 1881

Our first Sunday ashore — a splendid pleasant day. The wind has changed and
is now in our favor. Wafting us along with the aid of steam at a splendid rate.


## July 11th, 1881

A mild pleasant day until about 4 p.m. when wind hauled ahead and increased
in force so that it now threatens to become a gale. No observation has been made as
weather persists.

## Tuesday July 12th, 1881

The wind still adverse. The temperature has fallen very low and indicates the
presence of ice. At 8 p.m. we fall in with the ice — a long narrow strip of freed ice
through which we cautiously steam at half speed. Following the tortuous channel
which the openings in the ice afford.

The crows nest has been hoisted up to the fore-top-gallant masthead and in it
the Second Mate stands and directs the movement of the ship. The presence of the
ice has calmed the sea and we are surrounded with a most beautiful scene — the
beautiful blue-green edges of the ice blending with the reflections of the setting sun
present a panorama of rare beauty resembling some rare mosaic in a grand scale.

## Tuesday July 12th, 1881

In the foreground can be seen several seals of the harp species. Lt.
Kislingbury hazards several shots at them but without affect as the distance is great.
Occasionally a mammoth whale can be seen emerging like some miniature island
among the ice and water, sending a spout of water which dyed with the tints of the
setting sun, present all the colors of the rainbow. Our position can only be
ascertained by dead reckoning as no meridian observation has been made. We place
this floe of ice in Lat. 61° N.


## Wednesday July 13, 1881

Our party, or those who have been so unfortunate as to be seasick are
recovering their spirits in this water kept smooth by the ice. This Mal de mer has
visited our party pretty frequently without regard to age or station. I am so fortunate
as always to enjoy immunity from it. Lt. Greely has experienced its unpleasant
effects in large degree.

We fell in with another ice pack Lat. About 63° N. It presents the same appearance as
the former pack we met. The wind coming off it makes the temperature very cold
making us realize that we must expect to inhale Boreas’ chilly breath earlier than
anticipated. During our passage the prevailing winds have been from the North which
augers well for our success as the ice will be driven out of Smith Sound admitting of
our passage through it — We sighted land for the first time Friday.

## Thursday, July 14, 1881

We have been in --- since Friday. The sea is calm. A dense fog hangs over
everything. We are compelled to go half speed for fear of encountering bergs which
cannot be distinguished at any distance through the hazy fog.

The Capt. proudly relates an instance of the good Proteus’ ability — While
out on a sealing voyage she had just extricated herself from a pack and had attained
about the rate of half speed when before it could be avoided she ran head on into a
large berg. She actually ran several feet up the side of the berg so great had been the
momentum. She however, sustained no other injury than to destroy her head gear and
neck off the (cutwater). Such accounts of her prowess naturally inspire us with much
confidence. The fog lifts about 1 PM giving us another glimpse of the snow clad
mountains (?) along the seacoast.

## Friday, July 15th, 1881

We can occasionally see the land when the fog lifts. The Capt. and Mr. Israel,
both were successful in getting a meridian observation — our Latitude is 66° 42' N.
Land still in sight. I recognize the land very readily from my remembrance of last
years cruise. To a stranger from the south the weird appearance of these latitudes is
most remarkable and fascinating — a dark, bold striking coastline beyond which the
snow clad mountains ascending to dizzy altitudes can be seen as the gauzy curtain of
the fog lifts. The sea dotted with bergs presents no other obstruction to the eye and as
we again bring our eyes to land we are impressed with the silent and desolate
appearance of land — no sign of animal or vegetable life disturbs or beautifies the
scene. Silence reigns supreme.”

## Saturday, July 16th - 1881

The fog has again settled down this morning and as we are supposed to be in
the latitude of Disco the ships speed is lessened. We are reckoned to be very near
Godhaven at 2 p.m. and the engines are stopped in a useless attempt to make the lands----to the
dense fog which still prevails. At 8 p.m. to our great delight the fog lifted like some
high curtain rolled back showing the snow clad island of Disco close by.

As the fog dispersed it presented a most beautiful sight — the dark coast
plentifully dotted with glistening bergs — the highland covered with snow, an
occasional streams of ice water trickling it’s way like some silver ribbon over ice and
rocks to the sea below and the fog, like a halo draping the highest peaks. But as we
drew nearer no sign of sunny summer could be seen except a few patches of hardy
grass struggling in favored spots and in the valleys the beautiful green velvety moss
which gives to this land of desolation its name.

## Saturday, July16th 1881

I instantly recognized the conformation of the land from my recollection of
my trip on the Gulnare last year and was able to direct the way to the Harbor of
Godhavn which we soon reached and dropped anchor about 10p.m. The sun was still
up and the little basin like harbor looked very peaceful and inviting as we steamed
into it.

It was calm and still as a duck pond and in the glassy water, which was clear as
chrystal, was reflected the towering, frowning cliffs which surround it. The picturesque
Esquimaux in their furry costumes were gliding over the water towards us in their
graceful and fairylike kayaks, and the pantalooned maidens tripped down to the rocks
to get a nearer view of us. It is all so novel and charming that those of us that have
not been here before cannot repress the greatest interest and curiosity in surrounding
so strange and unlike the civilization we have left.

Dr. Pavy and Henry Clay who are expected to join us near Rittenbank distant
about 70 miles. We will leave here in a few days for Rittenbank and will then
precede to Upernavik, our last stopping place until our destination is reached. From
information inspector Smith gives us, we are to infer that our chances of getting
through the ice this year are very good. The winter in Greenland has been a very mild
one and reports from the northern stations state navigation clear of ice.[^icenote]


[^firstinternationalpolaryear]: See the Wikipedia article on the [First International Polar Year](https://en.wikipedia.org/wiki/International_Polar_Year#The_First_International_Polar_Year_(1882%E2%80%931883)), an international cooperative to obtain scientific observations of the Arctic by a varied group of nations.
[^icenote]: This feels like a premonition, or foreboding knowing that ice would keep their relief ships from being able to reach them with supplies or for rescue.
