---
title: "1881-07-29:1881-08-02"
subtitle: |
  Leaving Upernavik
date: 2024-03-03
categories: [rice, diary, arctic]
editor_options:
  chunk_output_type: console
bibliography: refs.bib
---

## 1881-07-29

We left Upernavik today at 4:30 p.m.
All hands were busy in writing letters before starting.
These go by a Danish ship which will soon leave Greenland for Copenhagen.
I sent letter to Herald.

Inspector and Governor Elberg came and bad us farewell, not leaving the ship until we had passed out of the harbor.

## 1881-07-30

We found very little ice.
It has been the experience of almost all voyagers to fall in with the ice pack after leaving Upernavik.
Our departure furnished us much food for reflection.
Upernavik is the last point at which the least semblance of civilization can be found.
Our course now leads us to that vague, unknown region which is so indefinitely marked out as to be undefined.
Our ship now plows water that have seldom been disturbed.
No sails whiten the broad expanse of dark blue water.
In their stead, the stately bergs move majestically along.
One can scarcely refrain from descanting on the beauties of these bergs whenever the subject is suggested.
To think of them only as immense islands of ice conveys no idea of their remarkable beauty when lighted up by the peculiar rays of the midnight sun.

Today, when in latitude about 74&deg; 34', considerable excitement was occasioned by the discovery of a veritable polar bear.
We had steamed into a small pack of ice extending in a narrow belt and his bearship was seen on one of the pieces of ice enjoying an evening meal off a seal he had caught.
A Bear!
A Bear! was shouted in excited tones all over the ship, and soon our hunters were seen emergine with their rifles.
The bear was a few hundred yards from the ship and from a number of shots fired one or two bullets hit him.
He had hitherto been perfectly indifferent to our approach, but, finding it disagreeable for him, he took to the water, swam a distance, and emerged to crawl upon the ice again.
By this time a boat was lowered and Lieuts. Kislingbury and Lockwood with Mr. Clay rowed nearer, despatched him, and brought the body triumphantly aboard.
As soon as he was hoisted on deck and placed in position, I proceeded to make a photograph of him.
It was a young make and proved to be in fine condition.
Our two Esquimaux were in their element dressing the carcase, and soon had it hanging up.

## 1881-07-31

We are making good progress north.
It is considered strange that no large pack of ice has been met.
We fell in today with a small pack, but soon steamed through it.
Several seals of the square flipper kind were seen on the ice and we succeeded in shooting one, which I photographed when brought on board.

The bear meat which we had for breakfast proved quite palatable, although tasting a little fishy, the ducks have reconciled us that taste; the bear was not more fishy than they.

Our faire will be varied still further by the meat of the seal, which is considered excellent.

## 1881-08-01

The fog has been setting down but fortunately cleared away by the time we sighted Cape Dudley Digges.
We soon after made the Carey Islands, and the Proteus stood in to the land, remaining about three hours.
A large party of us landed.
The cairn erected by Capt Allen Young was examined and a record found, which we brought away, leaving a copy to which Lieut. Greely added a short account of our own progress.
A letter addressed to Sir George Nares was also found.
While we were at the cairn another division of the party found and examined the cache of stores or rations left by Sir George.
Trey were in good condition.
The rum was tested and pronounced excellent.
Several cans of the meat were brought on board, and appeared to be as good as when deposited six years ago.
The biscuit was, however, mouldy in part about one fourth being spoiled.

## 1881-08-02

This morning we had the pleasure of sighting Cape Alexander, at the entrance of Smith Sound.
We soon steamed by, passing the celebrated Crystal Palace glacier and Crystal Palace cliffs.
Cape Alexander is in latitude 78&deg; 10', and, as it is considered the key to the unknown Arctic, considerable exultation was felt.
"We are within eighteen degrees of the pole," said Lieut. Greely, "if we never get any nearer,". 
Soon we passed Port Foulke, Dr. Hayes winter quarters, and anchored about noon by Littleton Island.
Capt. Allen Young, in the Pandora, left letters here for the Alert and Discovery, which were recovered by these ships as they were on their way home, and were south of the place when Capt Young deposited.
It was also about this place that the ill starred Polaris was lost, and on the mainland the party, under Capt. Buddington, wintered.
