---
title: "1881-08-01:1881-08-07"
subtitle: |
  Moving north, finally finding ice.
date: 2024-04-12T02:00
categories: [diary, rice, ice]
editor_options:
  chunk_output_type: console
order: 4
---

## Monday, August 1st 1881

The fog has been settling down here. Fortunately cleared away by the time
we saw Cape Dudley Diggs. We soon after made the Carey Islands and the Proteus
stood in to the land remaining about three hours. A large party of us landed. The
Cairn erected by Capt. Allan Young was examined and a record found which we
brought away leaving a copy to which Lt. Greely added a short account of our own
progress. A letter addressed to Sir George Nares was also found. While we were at
the cairn another division of our party formed and examined the cache of stores or
rations left by Sir George Haines. They were found in good condition. The rum was
tested and found excellent. Several cans of the meat was brought on board and
appeared to be as good as when deposited there six years ago. The biscuit was
however moldy in part — probably one fourth of it being spoiled.

## Tuesday, Aug 2, 1881

This morning we had the pleasure of sighting Cape Alexander at entrance to
Smith Sound we soon steaed by passing the celebrated Chrystal (sic) Palace Glacier
and Chrystal Palace cliffs. Cape Alexander in Lat 78° 10’N and is considered the key
to the unknown Arctic. Considerable exultation was felt.

"We are within 8 degrees of the Pole”, says Lt. Greely — If we never get any
nearer.” We soon passed Port Foulke — Dr. Hayes winter quarters and anchored
about near by Lyttleton (sic) Island. Capt Allen Young in the ‘Pandora’ left letters
here for the Alert and Discovery which were never recovered by the latter ships as
they were on their way home and were south of this place when Capt Young
departed. It was also about this place that the ill starred Polaris was lost and on the
mainland the party under Captain Buddington mutinied — so we had abundant interest
in going ashore here. One party under Lt.Greely went to Cove for the bag of letters and
another with Lt. Kislingbury to find the Polaris quarters — or what remained — to the
latter I attached myself taking my photographic apparatus along — after a row of
about 2 miles we entered Lifeboat Cove and after tramping around discovered a
demolished cairn, probably by the Indians, and broken scientific instrument including
a transit, strewn about. Further on we found remains of their quarters — stoves, nails,
locks, instruments, etc. etc. The time passed very quickly as we handled and looked
over the articles so unceremoniously left behind when the Ravenscraig brought the
storm tossed party such a happy delivery. I photographed the site and also made a few
of Lifeboat Cove. An adventure awaited us on our return. While paddling across
Lifeboat Cove a school of walruses were seen disporting themselves in the water.
We cautiously approached them and soon a well directed bullet was lodged in
the neck of a large female. The herd deserted her and her calf emitting the most
piteous sound was seen crawling on the neck of the mother. The water was dyed
with blood. Clay succeeded in hitting the calf and no doubt killed it — as it sank at
once an did not rise again. The mother dove but soon came up again and again
struck. She now came directly for the boat. With evident warlike intentions. Waiting
until she was within twenty feet of the boat Lt. K and Clay fired simultaneously, the
two bullets rattling in her open mouth down her throat. We waited for her to rise
again but nothing more was seen of her. I have no doubt that both the mother and the
calf were killed as they always sink when shot. A harpoon is required to save them.

We found Lt. Greely and his party on shore. They shortly after came in
loaded with kegs and boxes of letters and pemmican that had been left for the Nares
party. Lt. G. will send then by the to go to England via Newfoundland.


## Wednesday August 3rd, 1881

Lyttleton Island is in Lat 78° 23' N, long. 73° 30'W. Left there last night and
was surprised and more than pleased to find open water. A most beautiful morning —
the sea calm as a duck pond reflecting back the dark cliffs with unmistakable
distinctiveness. Photographed Bache Island at a distance of 20 miles from the ship —
Also photographed Cape Hawks and Washington Irving Island at a distance of 8
miles. These photographs on account of the great distance and remarkable reflection
fogging the plates and disadvantage of making them from the ship while in motion,
are not very good negatives. But were fine for geographical purposes. — While Lt.
Greely was ashore examining the depot left at Cape Hawks (where we arrived at 8:30
a.m.), I was landed on piece of floe ice and from that position made photographs of
the surrounding land, Cape Hawks and Washington Irving Island. Lt. Greely found
boat and stores which were brought aboard — left Cape Hawks at 11 a.m.

## August 4th, 1881

We are having a most remarkable run. No obstructions are met with. These
waters so difficult of navigation are as clear as can be wished for. We Passed Cape
Fraser at 2:50 p.m. having accomplished in sixteen hours the distance from Lyttleton
Island that occupied the English expedition twenty one days to make. The experience
of all who passed up Smith Sound has been that the passage is difficult to make and
nothing but the most untiring and energetic warfare with the ice will enable any ship
to pass and then only when the season is favorable. Our experience is without
precedent and cannot be accounted for. Passed Cape Constitution, mountains highest
and now at 9:40 p.m. after several delays on account of fog and detours to avoid ice
we meet the main pack — solid and forbidding — The ice appears solid and densely
packed, no channels or openings with 
Capes Lieber and Baird on the side and Thank God Harbor and the celebrated
Petermann Fiord on the other, only 10 miles from our destination. We are as
completely cut off from it as if this ice had met us at a lower latitude. After steaming
around to see if any opening presented the ice, anchors were brought out and the old
Proteus made fast to the ice to await further developments. Latitude 81°36’ N
4:30 p.m. part of the edge ice on fringe which appears to be thinner than the main —
The pack appears to be very compact and shows no signs of breaking up — at
breaks up. We left in morning, go amid large pieces, in shots moving down and ran to
the west and fastened in ice again at 7 p.m. — at 7:30 ice compelled us to make
another small change. The fog is alternatively lifting and settling down upon us.


## Saturday August 6th, 1881

A beautiful day, calm and clear. The water as glassy as Fairmount Park — I
photograph ice, Cape Lieber and surroundings — Narwhals and white whales were
seen. The Esquimaux succeeded in fastening to one of the fish, but it escaped by
going under the ice and breaking off the string of harpoons.

## Sunday August 7th, 1881

At 3:30 a.m. tried to force ship through channel in ice but the attempt was
ineffectual. Fastened to the floe again not shifting till 3 p.m. when we moved to the
Southward. Unless the ice will break-up and leave us a channel we shall be forced too
far to enable us to reach Lady Franklin Bay this season and be compelled to seek
winter quarters on a lower latitude. I am apprehensive that we will be caught in the
pack and held firmly. The pack as it moves taking us down Smith Sound as it did the
Polaris. The outcome is rather disconcerting when we consider how nearly we
attained out destination. To be forced back now after getting a sight of our goal will
be a greater disappointment than the same results if the difficulty had been met
earlier.
