---
title: "1881-08-22:1881-08-31"
subtitle: |
  Building the house.
date: 2024-04-13T03:00
categories: [diary, rice, ice]
editor_options:
  chunk_output_type: console
order: 6
---

## Monday, August 22nd, 1881

Light snow fell. The dogs are still dying off. Dr. Payve with the aid of
Esquimaux Jens and Frederick is doing all that is possible to save them. Sulphur was
administered.
Dr. Myself and the Esquimaux made a second trip to Water Course Bay after
the two carcasses of musk oxen. Took tent poles along and tied the meat up. Found
the foxes had devoured some of the meat (see private journal this date)


## Tuesday, August 23rd 1881

Still busily engaged on the house. I am compelled to rest for a couple of days
to recover from a strain I gave myself in the lifting the muskoxen at Water Course
Bay.


## Wednesday, August 24th, 1881

Our house is so nearly completed that most of the party have deserted their
tents and moved into the house. I still remain in the tent, as I anticipate that life in the
house will be so monotonous during the long dark winter that the longer I camp out
the better as the change will be more agreeable

## August 25th, 1881

My tentmates Jewell and Israel today transferred themselves to the house. I
am left the sole occupant of the tent. I find it rather cool, but there is much comfort
and pleasure in crawling into a warm deerskin sleeping bag. I find reading a pleasant
occupation, although the conditions are entirely different from those under which this
recreation is generally indulged in. After shooting myself as a sword into the fur
scabbard of my sleeping bag, I draw the bag up under my chin and putting on cap and
mittens enjoy myself with Dickens or the less enjoyable, but more instructive legal
works of Kelent: A sense of comfort is experienced not withstanding the fact that the
snow can be heard whirling against the canvas of the tent. And this is August. Today
the “Proteus” heretofore unable to get away, succeeded in getting through the ice and
passed out of sight. We cannot know of course what her success will be in getting out
of Smith Sound until next year. Lt. Kislingbury on account of some dissatisfaction
with the commanders management desired to go back. Permission was granted and he
prepared to return by the Proteus, but before he could reach her, she passed out and
he was compelled to remain.

## August 26th, 1881

A severe snow storm set in during last night, it snowed all day Friday. I spent
most of the time in sleeping bag reading. The work on the house could only be carried
on inside and afforded opportunities for but few of our number to work at the same
time.


## Saturday August 27th, 1881

The snow continued to fall at intervals today.


## Sunday August 28th, 1881

Cleared up.



## Monday, August 29th, 1881

The Dr. and I were busy making preparations for a pedestrian trip to
Lincoln Bay to examine the depot of provisions left by the English Expdn of '75-76.
We started at 7P.M. on our trip carrying a small tent, blankets, cooking apparatus
 alcohol and rations. Ralston and Linn accompanied us as far as St Patrick's Bay at 1 a.m. on 
the 30th and camped all night. The weather was extremely cold. The thermometer was
down to zero.

## Tuesday, August 30th, 1881

The fog was so dense in the morning that we did not attempt to travel as we
were uncertain which of two routes to take and could not decide until a view was
afforded.

The fog cleared up and we started from camp at 2 p.m. Traveled over very rough
country and at 3 p.m. commenced descending the mountain side to the stream running
into St. Patrick’s Bay, a most difficult task as the ground was rough and rocky and the
decline very steep. Observed a strongly marked fog 4 p.m. It contained all the
colors of the rainbow. We passed the stream at 6 p.m. and after ascending the hill on
the other side we continued until we had traveled 10 hours, where we camp at 12
midnight in the neighborhood of Cape Beechy. We were compelled to sup on frozen
preserve of meat and biscuit. With our alcohol lamp we melted enough snow to
quench our thirst. The minimum thermometer registered +5 during the night.

## Wednesday, August 31st, 1881

We packed up, and made another start at 11:30a.m. We were compelled to make
another difficult descent to the ravine at Cape Beechy. I saw numerous tracks of
muskoxen and following them fell in with a herd of nine muskoxen. While the Dr.
was engaged in making a cache of some of our rations for use on our return, I made a
detour around one of the hills and attempted a shot at them with the large Colt
revolver. I aimed but with without any result. They scampered off in a remarkably active
manner considering their clumsy appearance. Their hair is very long and hangs from
their belly nearly to the ground giving them an extemeley short legged appearance,
but their agility can not be questioned as they will climb up the sides of an almost
perpendicular cliff without difficulty. We render our way to the shore and attempted
to reach Wrangel Bay by the ice foot. We only reached the “Blade Cliffs” where we
found the ice foot completely washed away and the cliffs descending almost
perpendicular to the water. It was impossible to span, or to climb up to the plateau or
top of mountain. We were compelled to retrace out steps and camped at foot of ravine
at 1:30 a.m. Sept 1st.
