---
title: "1881-09-16:1881-09-23"
subtitle: |
  Expeditions and wolves.
date: 2024-04-14T05:00
categories: [diary, rice, camp]
editor_options:
  chunk_output_type: console
order: 9
---

## Friday, September 16, 1881

Lt. Greely with Brainard and Bender started out to visit the United States
Range of mountains. Connell was to accompany them one day's march to assist in
carrying the outfit, etc. Lt. Greely returns at 3 p.m. His knee goes out and Connell
went on instead.

Henry and I set poisoned meat for the wolves in the valley near Mt. Cartnell. This is
my first trip from camp since my return. The wolves have completely shredded the
hides and cleaned the heads of the dead muskoxen.

## Saturday, September 17, 1881

The snow fell all day today. The commanding officer has given out that on
the birthday of each member of the party a celebration of the event shall take place to
such as the circumstances will permit. The member who’s birthday is celebrated shall
on that day be exempt from all duty and shall have the privilege of making out the bill
of fare for the dinner which will be the grand event of the day. In the evening a quart
of rum is to be issued. Today is Whistlers birthday and he inaugurates the system.


## Sunday September 18,1881

Lt. Greely reads a chapter from the Bible aloud to us every Sunday moming.
This with a prayer read for those who desire, comprising our religious services.
Brainard and party return at 8 P.M. They did not reach the United States Range.

## Monday September19, 1881

Jewell’s birthday. He makes out a bill of fare which furnishes us with a grand
dinner considering our distance from market. The temperature very cold for this
season of the year. The thermometer registered -10, 42 degrees below the freezing
point. Rather cold weather for Indian summer.



## Tuesday September 20, 1881

Dr with Linn and Jewell attempt to carry rations to Cape to be cached there
for the use of the party which is expected to go to Cape Joseph Henry later in the
season. They get to Distant Cape when they find open water and the ice foot being
rough and much obstructed, the Dr. decided to leave the rations there until later when
the ice shall have formed. On the return of the party Lt. Greely decides to make an
attempt himself as he considers the difficulty not sufficient to deter a party from
getting around Distant Cape. He was over yesterday and examined the ground. Lt G.
selects Brainard and I to assist him. We start at 1 p.m. with dogs and sledges.
Frederick the Esquimaux is our driver. With great difficulty we succeeded in getting
almost to Watercourse Bay when one sledge broke down and we were obliged to
return.

## Wednesday Sept 21, 1881

This morning, the sledge having been repaired, Brainard, Linn and I start to
complete the work commenced yesterday. Having noticed several floebergs that
would make good subjects for pictures, I took my photographic apparatus along. Left
it at Distant Cape as I did not wish to risk it on the other sledge over the rough
icefoot. After assisting Brainard over the most difficult of the way, I left them at the
entrance of Watercourse Bay, and returned for the photo outfit. By the time I again
reached Watercourse Bay where the most striking bergs were, it had commenced
snowing and I had succeeded in getting but indifferent light on the subjects. I exposed
the plates and leaving the apparatus to be brought in by the sledge I returned to the
quarters overland reaching camp at 6 p.m. On arriving I learned that the large
hospital tent used as a carpenter’s shop had been burned down causing considerable
excitement. At one time it threatened to communicate the flames to the house, our
quarters as the tent was very near the latter. Ellison had his chest of carpenters tools
and Biederbeck lost most of his underclothing which he had washed and left drying in
the tent. Brainard and Linn returned at 8 p.m. They deposited the provisions on the
north side of St. Patrick’s Bay.

## Friday, September 23, 1881

This morning Lt. Kislingbury and I visit the musk ox offal to see if the poison
we had laid for them had brought about any results. We found two victims stretched
stark and stiff. They were both females with beautiful white coats. We carried them
both to camp a difficult task as the distance was fully a mile. They weighed 57 and
61 pounds respectively. They appeared much larger than their weight indicates as
they are very gaunt and thin. Their coats were beautiful, long white fur with a few
black hairs along the back. They measured five feet from tip of tail to nose. I
photographed one of them.
