---
title: "1881-10-06:1881-10-13"
subtitle: |
  Setting up more depots.
date: 2024-05-05T00:00
categories: [diary, rice, camp]
editor_options:
  chunk_output_type: console
order: 11
---

## Thursday October 6, 1881

Our chief object in visiting the Bellows was to have the muskox meat left by
the party in Sept. from the place the cattle had been killed to the icefoot that it might
be convenient for a party to take home to camp.

Arose at 6:30 a.m. Cooked breakfast over our alcohol lamp. Minimum temperature
recorded -24 during night.

Started for a load of the meat, found it about 2 miles from the shore, and
brought down one carcass, a difficult matter to drag the sledge with such a load as the
stones were not covered by the snow.

It was very uncomfortable as a strong breeze was blowing causing us to suffer
much from the cold. It required the utmost vigilance to prevent our faces and hands
from freezing. Brainard had his nose frostbitten several times and despite my caution
I had my cheeks frozen. By 4 p.m. we had hauled four loads of the meat to the shore.
We then went to the tent and prepared a hasty meal, and at 4:30 started again for
another load. At 4 the thermometer read -18 and at 4:20 when we left the tent it
registered -20.

Returned at 7p.m. tired out and cold. The thermometer showed us the temperature had
fallen to -25° F.

## Friday October 7th, 1881

After another uncomfortable night we got up early to bring the last remaining
carcass of meat down. Temperature during night -25. Started for home station at
10:40 a.m. Arrived home at 5 p.m. It was then very dark and snowing steadily.”

A footnote “I made one exposure for negatives at “Bellows”.


## Saturday October 8th, 1881

Snow falling from 3:30 a.m. ‘till 6:10 p.m., The thickness of the ice measured
near tide gauge. Result of 5 ft. 7inches. Two mock moons were observed.
Temperature +6 to -6.


## Sunday, October 9, 1881

Light snow falling most of the day. Dr. Pavy and Whistler return from their
attempt to reach Cape Joseph Henry at 4:30 p.m. they were unable to reach it owing
to the straights being still open and no ice foot on which to travel near Lincoln Bay.


Temperature ranged from +1 to -16. Sunday services and rum as usual.

## Monday October 10, 1881

Weather very thick during day. Snowed from 5 p.m. to 9 p.m. Lt Lockwood
and Sgt. Jewell started to walk to Cape Baird at 8 a.m. Their object is to determine if
sledging to that point is practicable. They return at 8:40 p.m. We had become
anxious about them as it had become very dark. A party with lanterns met them
about 3 miles from camp. Thermometer, Maximum -1, minimum -11.9.


## Tuesday October 11, 1881

Israel took deep sea temperature today. Sgt Linn with the two Eskimos and
dog teams started for the “Bellows” to bring back a load of meat. Temperature,
Maximun -2 to minimum -19.


## Wednesday October 12th 1881

Lt. Lockwood started this morming with three men for the purpose of
establishing a depot at Cape Baird. Linn returned at noon with 927 pounds of
muskox meat from the Bellows. A Solar halo (mock suns) was observed close to the
horizon at 11a.m.

Very low temperature today, the thermometer reads from -8 to -25.9 —rather cool for
Indian summer.

## Thursday October 13th, 1881

“Brainard and I started for Mt. Ovibus, distant to base six miles. We rode part
of the way with Linn who was on his way to the Bellows after more meat. Mt.
Ovibus is estimated to be 2600 ft high. Our object was to reach the summit and
examine with the telescope the valley leading from Muskox Bay to see if it offered a
practical route to United States range of mountains. We were three hours in making
the ascent from base at some places the climbing was most difficult and found a
heavy deposit of snow at the top of the mountain. We were forced to use our 
snowshoes which we fortunately carried. It was my first attempt at walking with such
foot gear, and I found I could travel comfortably. We did not accomplish anything as 
the atmosphere was hazy and could see no distance. 
Reached home at 5:30 p.m.


Lockwood and party returned at 7:45p.m.
Linn got back at noon with the remainder of the Musk Ox meat from the Bellows.

Weather fair- low temperature

Maximum -11.

Minimum -27.4

The above thermometer readings are for the 24 hours froml2 midnight to 12
midnight. The same now applies to all the temperatures I have herein recorded.
