---
title: "1882-03-15:1882-03-22"
subtitle: |
  Putting out provisions.
date: 2024-08-08T15:45
categories: [diary, rice]
editor_options:
  chunk_output_type: console
order: 27
---


## Wednesday March 15th 1882

I was busy all day making some more photographs and preparing for our start
on Saturday. I made one negative of dogs hauling ice which turned out very well, the
dogs having kept perfectly still during the exposure. Lt.’s Kislingbury and Greely and
also Cross and Jens were included in the group.


## Thursday March 16th 1882

Almost crazed getting ready for our start. Clothing to be collected, cooking
gear to look after, etc. The Dr. has taken a wise plan; he and I had made a complete
list of all that we are required to take and divided this again and each of us looking up
and preparing the articles set down on our list and checking the same when added to
our pile in the lean-to. The brains are racked to remember every little thing as
anything left behind cannot be replaced.

Max: -32.1 Min: -42.2.


## Friday March 17th 1882

Was a cold St Patrick’s day, Max:-30.6 Min:-35.6

## Saturday March 18th 1882

Our preparations are now complete and will start tomorrow morning. A good
dinner and a quart of ardent enlivened the last evening we shall spend under roof for
some time.

## Sunday March 19th 1882

This morning at 9:40 a.m. accompanied by Jewell and Fred the Esquimaux we
made our start for the North. Jewell will return after supporting us as far as Lincoln
Bay. Our party will then consist of but three persons, Dr. Pavy, myself and the driver
Jens. Nine dogs to our team and 8 to Jewells. The morning was cloudy and a little
blustery but afterwards improved. I made a photograph of the outfit including myself
also in the picture with Gardiner to make the exposure. Lt. Kislingbury walked with
us as far as Cape Murchison where he bade us “Godspeed” and we pursued our way.
Temp when started was only -24 but was ten degrees lower when we reached Depot
“B” at Shift Rudder Bay where we arrived at 3:40 p.m.

We found the party of seven just returned from Greenland shore. Their
experience was a very trying and unpleasant one, and the temperatures they were
called to withstand were probably lower than have ever been recorded by parties in
the field. When their first camp was made the temp stood -53 and during the night fell
below -61 the point at which their thermometer was graduated and below which there
was no registry—the index point was forced below the scale and stood in the bulb.
Schneider gave up first day out from Depot “B” and was sent back to the snowhouse
with Biederbeck with nurse (see sledge journal) not one of the party has escaped
injured fingers and scarified noses and cheeks. The large party crowded us out
of the snowhouse so Jewell and I dug a hole in a large bank of closely packed snow
and in this we passed a fairly comfortable night. At an early hour we were aroused by
the seven sleepers arriving at our igloo to bid us goodbye and we drowsily pulled
aside the flap of our sleeping bags to reply to their salutation. Lynn crawled on top of
our fragile crystal palace to shout his good wishes the ventilation hole in the roof. To
show a proper amount of appreciation we turned our faces, Jewell and I, in the
direction from which the sound issued, when crash came a swaddled foot through the
snowy chill precipitating on our smiling upturned faces clouds and huge blocks of
frosty snow. Lynn avers that he saw clouds of sulphur escape as he beat a hasty
retreat to join his companions. Temp at midnight in hut -1 outside the thermometer
was ---39.



## Monday March 20th 1882

After the early start of Brainards party for the home Station we got another
nap. Started at 10 a.m.: the day gloomy and unpleasant. We found the traveling on ice
foot very good for some distance when we were compelled to take to the strait where
to ice was rough beyond description. The piled up masses of ice disputed our right of
way on the ice foot, and the straits were only to be traveled over the most disruptive
of rubble ice crushed into the greatest irregularity and unevenness by the tides and
currents in the fall before the frost cemented it together. It conveyed more the
impression of a stormy sea
lashed into fury and frozen instantly into immobility. Temp during day 20 below
zero but with a SE blowing made traveling very uncomfortable. Snow began to fall
and at 6:30 p.m. had so increased that we could not see our way and so went into
camp on the icefoot between Cape Beechy and Wrangle Bay. Jewell and I dug
snowhouse while Dr. and Jens fed the dogs. The moment we camped they curled
themselves like hedgehogs and the snow dusting about them soon enveloped them in
a white sheet beneath which they slept until the smell of chopped pemmican brought
them to their feet when it necessary for one of the drivers, me, to keep them in
abeyance while the others scattered the food in the snow. The restraint was then
withdrawn when there was a rush—snarl—and the frozen meal was dispatched at
almost one gulp by the wolfish animals. They then burrowed again the snow where
they remained quiet until near morning when they were sufficiently rested to again
prance around disturbing our rest by their snarling at and quarreling with each other.
The dogs of one team appeared to be the sworn enemies of the other and woe betide
the luckless dog that wanders into the enemies camp. Unless his friends, generalled
by the King dog, can come to the rescue, a sad remnant of caninity is all that will be
left to hobble back to his comrades. Barometer has been falling all day.

## Tuesday March 21st 1882

Weather was still thick and threatening when we emerged from our burrow in
the snow this morning. We did not get started before noon. The temp was mild -10,
but the wind was still blowing. We had great difficulty in proceeding, the high tides
harassing us along the icefoot. (I) know of nothing I can compare the nature of ice to.
I have never seen rocks on land so dispersed as to make so uneven a surface as the
rubble ice over which we traveled. One of us would advance with an axe to pick out a
route and reduce obstructions when necessary. The other, one at the upstanders
steering and pushing, the driver at the lines winding the dogs through the narrow
openings among the hummocks and rubble, followed slowly and laboriously and
notwithstanding our care the sledges (were) upset twice and the runner of Jens so
wrenched that it was necessary to unload and relash it. It is surprising the amount of
rough usage the Esk. sledges will stand. They are put together entirely with lashings
of walrus hide and when loaded—as they were—with over 600 Ibs. each, they will go
over a track of such roughness that the dogs themselves have to climb and jump over
the obstacle. One runner will glide up over a sharp block of ice from a few feet high
while the other falls in some crevice below. The whole weight is thrown on the latter
which is turned over on its side until it touches the crosspieces. Presently the sledge
will emerge bound off into a smooth place and land on its feet like a cat—the elastic
thongs bringing the runner again vertically under the sledge.

We arrived at Wrangle Bay at 7:30 and for the first time since leaving the
Station erected our tent which—intended to accommodate three—was too small to
shelter us all and Jewell and I made a small hole in the snow, just large enough to
admit of spreading out the sleeping bag where we spent a rather uncomfortable night
with the temp at only -24. My knees were swollen and rather stiff which made me
fear a possible attack of my old enemy the “acute”: but the morning reassured me to a
certain extent.

## Wednesday March 22nd 1882

Today after threading our way through some very rough ice we reached a
large floe of the paleocrystic ice of Sir George. On this ice the snow was sufficiently
glazed and hard to bear the sledges. We stopped at Mount Parry to pick up the cache
of provisions left there by the Dr. last autumn. On approaching the place we found the
tracks of large polar bear and on examination of the cache found that the brute had
eaten almost all the pemmican. He had also torn open the bag containing the hard
tack: but on not finding the contents palatable had scattered them among the snow
and turned his attention to the pemmican of which he made a lunch of almost 70 lbs!

Gathering up the remnants of the depot we proceeded, finding the traveling
very good over a strip of young ice that extended for a few miles towards Cape
Frederick VII. The icefront along this place presented a most remarkable appearance.
It was fully fifty feet high in an almost perpendicular wall and must have been created
under great pressure. The surface on which the sun blazed and glistened was as
polished and resplendent as a silver rampart studded with jewels.


We soon passed off the young ice and traveled over a succession of
paleocrystic floes which afforded even better travel than the season ice which was
covered with a salty effluence that made traction difficult. The only difficulty we
experienced was in passing from one floe to another where the edges were askew and
piled up, but even here the snow had drifted so that we could almost always find a
place where the chasm between the floes was edged over.

At 1 p.m. it was so calm and still that we stopped a short time to melt some ice and
quench our thirst. We were so comfortable and the weather looked so pleasant that we
were surprised to find that it was 36° below zero. We encountered some rough
traveling before we camped in Lincoln Bay about one mile north of the English depot
at 5:30 p.m. Jewell and I set to work to build another snowhouse on which we spent
two or three hours before its dimensions and finish suited us. We spent the (more)
time because we knew that it was to be our headquarters for some time while we are
advancing our provisions along the coast to the North.

Temperature at 6 p.m. was -35°
