---
title: "1882-04-11:1882-04-20"
subtitle: |
  More storms.
date: 2024-11-16T15:00
categories: [diary, rice]
editor_options:
  chunk_output_type: console
order: 31
---



## April 11th 1882

The gale brought with it as we before experienced warm temperatures and we
were much surprised at 3 a.m. the therm. reading +10. The wind had so decreased as
to enable us to move on. We proceeded to carry our load piecemeal over a few
hundred yds of rough icefoot that separated us from better traveling beyond. Two
hours after we were at “Floeberg Beach” -the winter quarters of HMS Alert in 1875-6.
It is in Lat 82° 27 North and the highest position on our globe that has ever been
attained by a ship. As we approach the sight of the British occupation evidence of
their stay met our view on every hand. What appeared to be two cairns were visible,
but —leaving the sledge at the ice foot we ascended a slight declivity and found the
first of supposed cairns to be the grave stone over the remains of poor Petersen, the
Danish interpreter who died from injuries received while on a sledge trip. The lonely
isolated position of his resting place overlooking the dreary frozen Polar Sea—far
from the haunts of men—surrounded this only ordinary proof of man’s mortality with
a peculiar melancholy interest. On the brass tablet that may never again be read by
mortal eyes was also an inscription to the memory to George Porter who was placed
in an icy casket on the floe a few miles north of this point. As we gazed upon the
boundless waste of snow and ice that met the weary eye we thought the inscription
“He shall wash me and I shall be whiter than the snow’”—beautifully appropriate. We
afterwards visited the cairn in which is deposited the records of the Alert and a list of
her ship’s company. The Dr. was instructed to bring with him the records—leaving
copies—but the iron safe or cask containing them could not be opened by us. The
cairn is an impressive structure and will long stand as a monument to the pluck of the
British sailor.

Leaving Cape Sheridan we cut across the floe for Harley’s Spit where we
arrived at 1 p.m. Temp +12. Our traveling from Cape Sheridan was principally over
paleocrystic ice with hard surface, but rolling and undulating and sometimes between
the floes rough and the chasm filled with soft snow. When near Harley’s Spit—as we
approached the shore we found the new snow lying much deeper outside it appeared
to have drifted off—



## Wednesday April 12th 1882

At 1 a.m. temp +3.5, snowing slightly, wind SW. at 2:45 a.m. we start back to
Black Cape leaving our tent standing here at Harley’s Spit with the load cached
inside. With our sledge light we traveled fast passing “Alert’s” winter quarters at 6
a.m. Beautiful moming with temp +4.

We reached our snow house at Black Cape at 9 a.m. We found that the gale
after we had left (1 suppose while we were at Rauson) had blown some of our traps at
least 500 yards. It must have raged with great violence as a bottle of mercury —for
our artificial horizon—had been blown about 300 yds. The entrance to snowhouse
was filled up and gave us about an hours work. Jens and I slept outside as I preferred
the sun to the gloomy atmosphere of the igloo. Dr. — more conservative slept in the
hut. We got up at 8 p.m. Min temp during our sleep -2, at 9 pm +1.

Getting supper (or breakfast) we loaded up and started for Harley’s Spit at
10:15 p.m. With a heavy load we made quite a long march to Harley Spit where we
arrived at 8:45 a.m. of 13th.


## Thursday April 13th 1882

We pulled into our sleeping bags after a splendid meal of English pemmican
which when fried we found to taste as good as sausage. It contained rather too much
pepper we thought. It was the most beautiful morning I had ever seen. The temp
above zero and the sun shining brightly on snow and ice. We had a fine view of the
coastline of both Grinnell and Greenland. The dark line of Grinnell Land terminating
with the lofty peaks near Cape Joseph Henry showed up with marvelous
distinctiveness and appeared so near that a day’s march would seem sufficient to
cover the distance. We knew better however. Appearances in the Arctic are deceitful.

## Friday April 14th 1882

With the sun shining through our tent and exerting its soporific influence over
our tired bodies we did not awake so early as we intended. We also after cooking our
meal spent some time in making a cache of a few days rations to be used on the
return.
We also left all superfluous articles of clothing and thinking the English cache at
View Point might contain enough spirit for fuel we also left our can of alcohol and
some dog pemmican. It was therefore 6 a.m. today before we started the dogs across
Marco Polo Bay for View Point. We started off very well but soon the soft snow
proved troublesome. It was just strong enough not to bear, and the sledge heavily
loaded would cut through bringing the dogs to a standstill from which they could not
be made to budge until the sledge was started again for them. This exertion would
send us thigh-deep in the snow after which our continued pushing would send up
through the crust at every step. The floes began to grow smaller and even sometimes
lined up with fringes of hummocks among which the snow lay soft and deep. The
passage from one floe to the other was often made with difficulty as they were often
separated by a deep trench with snow into which dogs and sledge, after leaving the
floe, almost disappeared. The ice here did not appear to have been broken up 
for at least one season as we saw no new ice between the floes and the
connection between them appeared of long standing. In fact the ice answered so much
the description of Com. Markham that we could readily believe not only that it was of
the same character—but the identical ice over which he traveled in 1876. Add a boat
to our load and the difficulties and progress would probably be the same. After about
seven hours of such traveling the dogs and driver appeared so tired that Dr. thought it
best to halt, thinking that with the approach of night the snow crust would harden
sufficiently to bear us. Under the lee of a large hammock we spread the sleeping bags
without erecting a tent at 1 p.m. Dr and Jens turned in for a few hours nap after we
cooked a pot of tea. I remained up. Temp began to fall as the sun declined and at 5
p.m. was -10, at 7 p.m. -13.5. Woke up Dr. and Jens and we cooked supper. Started at
9:15 p.m. Traveling no better. Did not proceed far before we cached part of the load
and proceeding with greater care. Soon struck some hard floes on which new snow
had not lodged. They were larger. We arrived at View Point at 3 a.m.

## Saturday April 15th 1882

At View Point at 3 a.m. Jens and I started back at once for the balance of our
load. Left the “dear bitch” with the Dr. as she is sick. We made good time and got
back to tent which we erected before we started at 9:30 a.m. Dr. was away looking up
the English caches. He returned while we were cooking our meal; had found the
cache at this place but saw nothing at Conical Hill.

Dr. and I go back to the cache and examine its contents. Find bacon,
pemmican and spirits and conclude that with these and the lime juice pemmican -
which we left at Harley’s Spit—we can get along for dog food on this trip and will
not have to return further than the place just mentioned. Even for them the load will
be light as in addition to the pemmican we will only fetch the alcohol pan. Weather
lovely—Jens and I very sleepy and turn in. Dr. has had nap during our absence and
we left him prowling around the coast. Temp at 1 p.m. +10 -comparatively hot.


## Sunday April 16th 1882

Fine morning, Jens and I with the dog team start for Harley’s Spit. Left tent
standing and took only sleeping bag and cooking apparatus with us. Traveled fast,
riding part of the way. Began to snow in a few hours after starting and could only find
our way by following old tracks. The sledge, light, handles with great ease even over
the worst places. We made Harley’s Spit by 1 p.m. Left View Point at 6 a.m.
Although the snow was falling we slept comfortably without shelter and warmed our
meal without difficulty.


## Monday April 17th 1882

We started at 2:30 a.m. for View Point. The alcohol and pemmican made the
load only a light one (about 130 lbs) and we traveled quite rapidly over the road that
was so well broken. Snow fell all day. We found the Dr. at View Point at 10 a.m.
Temp at 12 N +8.5 at 7 p.m. +1. Wind NW and freshening. After a sleep during the
day we arose in the evening and began preparing for a start north. Visited the cache
English and took from it whatever we required to complete our outfit. We appreciated
the pemmican, bacon and ram—which we used as fuel. We carefully secured a small
quantity of provisions—both for ourselves and dogs to be used on our return. Built
cairn over them. At 9:40 p.m. we started for Cape Joseph Henry but finding the
traveling exceedingly difficult and progress with it almost impossible we divided it,
and leaving part advanced with the remainder. One of the dogs—the dear bitch—was
so sick we tied her to the ice and left her until our return. We found the floes very
small and their edges greatly broken up and hummocky. The snowdrifts were also
deep and soft. After a struggle we
at last emerged from the snow drifts and hummocks and found a strip of young ice
that extended in length about two miles from Conical Hill forward to Cape Joseph
Henry. It was very narrow and the only proof of their having been any open water last
season that we had seen leaving the Alert’s winter quarters. The last new ice we had
seen was between Cape Rauson and Alert’s. This smooth stretch of ice promising
good traveling we unloaded and returned for the balance of the whole load, which we
had together by morning and hauled the whole along until 7:30 a.m.of the 18th where
we camped.



## Tuesday April 18th 1882

At 7:30 a.m. (as above) we halted and pitched our tent outside the icefoot and
nearly under the forming cliffs of Cape Joseph Henry. We were probably (?) about a
mile south of the extreme point. The Cape is a remarkable one — bold and striking and
standing — as it does — dark, frowning and forbidding — abutting The Great Frozen
Sea — provokes comment in its impressive fragments of ice in chaotic piles at its base,
“so far shall thou come and no further.”

In the evening we arose to make a start but found a storm so raging as to make
traveling out of the question. The wind was blowing from the South at least 30 miles
per hour directly on our faces accompanied by blinding drift. We found the dear bitch
dead, Jens stripped her of the harness and we threw her at the icefoot where the rising
tide soon encased her in ice and snow. Temp at 11 p.m. -10.


## Wednesday April 19th 1882

Still storming terribly. Our canvas tent flapped and whistled in the wind and
the ropes strained and surged in such a manner that at any moment we expected it to
be carried away. The dogs moaned and howled piteously and would come and lie
against the tent crowding in the sides until our sleeping space was painfully small. The
enforced inaction of our position - cramped in our sleeping bags — was extremely hard
to bear and more than once did we - encouraged by some momentary lull by the angry
winds — arise and essay a start: only to be driven back to cover by the storm. The rime
forming on the inside of the canvas shelter fell steadily upon the contents of the tent
insinuating itself into the mouth of the sleeping bag and our faces where the smallest
part was exposed. Temp during day from -10 to -12


## Thursday April 20th 1882

Weather still bad but our life cramped up in a sleeping bag with aching limbs,
was intolerable. So we made a start which resulted only in our placing a part of our
load a short distance above Cape Henry. The storm still raging compelled us to return
to our tent which we had left standing where it was pitched two days before. Not very
encouraging was the prospect afforded by our short trip. The small stretch of new ice
ended a little above our tent and to the North succeeded the terrible century ice, so
well described be Sir Geo Nares and his officers. It is impossible of course to convey
any idea of the roughness of its character for we have nothing to which it can be
compared. Dr. Hayes in his happy way spoke of traveling over much less formidable
ice as “like going over New York City on its house tops.”
