---
title: "1881-07-17:1881-07-23"
subtitle: |
  Sending mail
date: 2024-04-11T01:00
categories: [diary, rice, greenland]
editor_options:
  chunk_output_type: console
order: 2
---

## July 17th 1881

This morning we are informed that a boat leaves here for (?) where Danish
ship is lying about ready to start for Copenhagen and will carry our mail matter which
can be sent to us via Denmark. We are all therefore very busily employed writing to
friends and relatives. I send communication to the NY Herald repeating our chances
for getting through to Franklin Bay as well as we can judge from the outlook here.
The day is a very fine one. The bell in the primitive little mission church is calling
the -community to worship. Some of the men attend, Snyder volunteers his services
as organist to the small instrument which stands in the corner of the church. After the
service is over he pleases the Esquamaux much by playing them some lively music
which then attracted a much larger congregation than attended the worship. His music
which was interspersed with an occasional jig and dancing tune was rather un secular
and inappropriate for the Sabbath but we are compelled to admit that the natives were
more pleased with it than with the preceding — moral exercise. I meet the same faces I
saw when here last year. Mr. Smith is still Inspector, Governor Fleisher is Trader and
there have been no maternal changes in the Esqimaux population. They all pleased
with the ship which they consider much strong.

## Monday July 18th, 1881

It is difficult for me not noting the time to distinguish night and day here. The
sun does not set until about 11p.m. and is up again at 1 a.m. The morning and evening
twilight blend into one, casting a silver misty light over everything. I am writing this
in the calm at midnight without the aid of artificial light. The crew has been busy all
day shifting the cargo and putting more coals in the bunkers. Our men are bringing
off the lumber that was left by the Gulnare. Also the pemmican stores etc. It has

been too foggy for me to make photographs of Disco and the ship. On the day we
arrived here we noticed a magnificent iceberg near the mouth of the harbor. It was in
the form of an immense arch and presented a very impressive appearance. It was my
intention to return and photograph it at the first opportunity but we had hardly
reached our anchorage before it fell to pieces with a terrific crash louder than thunder.
The sea was disturbed for miles.

## Tuesday July 19th, 1881

I make several negatives today — photograph the Proteus and Godhavn harbor
 — I also make a group of the Governor’s family and Miss Smith and her governess.
They were very much pleased to have the opportunity of being photographed and
dressed themselves for the occasion with great care.” Miss Smith and her companion
looked particularly charming in the bright lively colors of the Danish peasant girl.

At least they look very charming to someone who does not expect to see another
female in a civilized costume for two years —

Lt. Greely purchased a quantity of whale skin for food — it is said to be an
excellent anti-scorbutic and is said to resemble tripe in flavor. It is in a dried state.

He also has contracted for dried fish and walrus meat which is to be the food
of the dogs. We will take in about 14 dogs here and will get others at Rittenbank and
at Upernavik. Inspector Smith and Capt. Fleisher are aiding our commander in every
possible way.

## Wednesday July 20, 1881

Took aboard fourteen dogs, with dog food for their consumption. It consists of
dried fish and walrus meat. The latter is most disagreeable in odor as it is partly
decomposed. But appears to be relished well by the dogs. Getting the animals on
board was a very exciting operation. They offered every resistance and yelped in a
most discordant and disagreeable manner. They are now penned in a small space on
deck where they snarl and snap at one another in the most unfriendly way. Several
encounters between the most warlike of the males has settled the question of
supremacy and now one battle scarred old veteran struts about master of the situation.

We are Ready to start but the fog is too dense to admit of going. Dr. Pavy arrived
from Rittenbank today looking well and relating H. Clay still in Rittenbank in good
health.

## Friday July 22, 1881

Left Rittenback this PM. for Upemavik. Will pass through Waigett, the strait
separating Disco Islands from the mainland.


## Saturday July 23, 1881

On the water — Still in the Waigett. The scenery through the strait is most
magnificent. The land is in sight most of the day. The frowning cliffs rise abruptly
from the sea which calmed by the numerous icebergs is as placid as the waters of
Central Park and reflects back the cliffs and the snow clad mountains behind them.
The stately bergs present the most beautiful feature of the panorama. Immense islands
of ice pure and white as Parian marble awaiting the sculptors chisel although no artist
could give them more beautiful and fantastic forms resembling at times the mosques
and minarets of some oriental city as the midnight sun dyes them with glorious tints.
The base is generally marked with a beautiful green where the dark blue water washes
over it.
