---
title: "1881-12-10:1881-12-18"
subtitle: |
  Jens tries to run away, and George fractures his shoulder.
date: 2024-06-16T16:00
categories: [diary, rice]
editor_options:
  chunk_output_type: console
order: 18
---

## Saturday Dec 10th 1881

Lt. snow during the afternoon. Lt Greely issued an order for all hands to return
at 11 p.m. as he considers it demoralizing to sleep at all times as we do now, as there
is no difference in the appearance of night and day.

## Sunday Dec 11th 1881

Our usual Sabbath, differing very little from the other days of the week. Lt.
Greely read the passage which is usually read at the opening of Congress this being
the day on which the event occurs. In the evening several of the cavalrymen gave a
very amusing imitation of the Indian war dance as they have seen it on the Frontier.
The falling of a remarkably bright was observed at 6:30 p.m. accompanied by a very
loud report. Auroral displays were seen at intervals during the day; at some times in
the form of streamers and at others in a curtain formation. They were of remarkable
brilliance. At 2:30. we observed the brightest arch that has been seen since our
arrival.


## Monday Dec 12th 1881

Cloudy weather. Light fall of snow. Party working on an ice wall to break the
cold draught at the corner of our quarters. I hauled a few loads of ice as usual.


## Tuesday Dec 13th 1881

Today Jens the Esquimaux concluded he would vary the monotony of our life
by absconding. His elopement was discovered at breakfast time. He had been seen in
the early morning however and we naturally concluded that he had not traveled far.
After breakfast Lt. Greely instructed Brainard and I to start from a point outside the
Station and by walking in opposite directions discovered (Jens) tracks leading from
the Station.

It was about 8:30 a.m. when we started. Henry volunteered to go with me and
Whistler went with Brainard. It was very dark, the sky overcast and no moon in the
heavens. Fortunately for Jens light snow had fallen the day previous so that his tracks
could be easily found and distinguished from others. I soon found his tracks following
the beaten track towards Dutch Island. We communicated with Brainard and Whistler
who soon found us and we proceeded at a rapid rate expecting to overtake the fugitive
in a short time as the track looked fresh and we knew that he had been very long on
the road. After proceeding a short distance we thought it best to send back word to the
Station to follow us with a dog team in case Jens should lead us a long chase. Henry
and Frederick the other Esquimaux returned.

Brainard Whistler and I followed the trail expecting to catch up to Jens at any
moment for we could see unaided by any lights he had not been able to follow the
path directly but wavered on and off. With our lanterns we moved on very rapidly
until Dutch Island distant two miles was reached. Beyond that point the path is not
well defined as it has not been traveled since the last party came in from Cape
Beechy. We saw that our game had turned off at right angles towards the ice foot so
as to follow the coastline and avoid being lost in the ice. His track now became
difficult to follow much time being lost in keeping (?) of them. When about five miles
from the home we were joined by Dr. Pavy with Frederick and dog team. We kept on
at the most rapid rate practicable, two of us going in advance with the lantern, the
others following the track as we found it. The ice foot was very rough and the
darkness was so intense that it was impossible to select the most favorable route for
the sledge even if the erratic course taken by Jens allowed for it.
When near Distant Cape the progress was very slow and at one place I
dropped behind to allow the Dr. a better position behind the sledge. We had been
walking behind it intending to join him as soon as the point was passed. I had just left
the advance and being able to hold on to the standards of the sledge and depend upon
it for guidance. I blew out the candle in my lantern to economize our light. As soon as
I dropped behind, the sledge disappeared in the dark and in groping my way after it I
met with several severe falls. I did not go far before I slipped and was thrown
violently against a projecting piece of ice. It was several minutes before I could move
from my prone position on the ice, when I discovered that my shoulder was
undoubtedly broken. I regained my footing and appreciating the importance of
catching up with the sledge, I lit my candle under great difficulty presented by the
wind and the use of one hand only. I started at the best gait I could suffering intensely
and encountered several more falls in one of which my light went out and delayed
me. I expected the sledge to wait for me at the moment they discovered my absence.
It appeared they were so interested in the chase that my absence was not noticed or
they thought I was following at my leisure. I plotted along my candle burnt out. I
overtook the party at a point a little south of Cape Murchison distant about ten miles
to reach while our (treacherous) way traveled much farther. They had just concluded
to wait for me. On learning (of) my condition Whistler started to return with me.


Brainard and the Dr. continuing in the way intending to go as far as Cape Beechy and
spending the night at the snowhouse if they did not find Jens. Whistler and I made but
slow progress on the return as 1 was compelled to avoid jarring my shoulder. When
near Distant Cape Whistler began to complain of the cold, a few moments after he
began to talk incoherently and before a mere halfway to Dutch Island he was
delirious. My position was becoming rather unpleasant.
Whistler overcome by the cold, was entirely unresponsive and it took all my
will and ingenuity to induce him to walk. He was continually falling down and could
hardly resist the temptation to remain on the ice. I attempted to lead him and having
no light our footing was so uncertain that I was continually jarred by missteps which
caused me to suffer intensely from my shoulder. I had to cajole, coax and command
Whistler at every step to get him along. I began to fear for his life: had he refused to
move he might have died in a very few moments.

We got as far as Dutch Island when Dr. Pavy, Brainard and the Esquimaux
overtook us with the dog sledge. I at once gave the Dr. the state of affairs and told
him it was necessary to get Whistler to the Station as soon as possible. It was
necessary to make him run behind the sledge and we learned on reaching the Station
that when near the Station they had to place him on the sledge as he had lost all use of
his limbs.

Brainard and I reached the Station at 4 p.m.

We had been out about 8 hours, traveled at least twenty miles with the
temperature at -30 on one of the darkest days of the winter. Whistler was delirious for
several hours, his nose and cheeks frozen but otherwise he suffered no bad
consequences. Dr. examined my shoulder and found fracture not complete but the
bone evidently cracked and ligature injured. Jens was overtaken a short distance
beyond the point from which we started to return. He came back quite penitently but
did not attempt to explain the cause of his strange conduct. Light snow was falling
almost all day.

## Wednesday Dec 14th 1881

A few days ago Lt. Greely requested me to try and arrange some sort of
entertainment as a diversion for the party the time hanging heavily on our hands at
present. I found it impossible to carry out any such plan successfully as our party is so
small that after making a cast of performers there would be but a small audience
remaining. Then it would be impossible to rehearse or arrange anything except in the
presence of the others so by the time of the performance the programme would be
stale and uninteresting. I therefore gave up the idea but suggested to the men that we
should invite Lt. Greely to lecture before us. They were pleased with the suggestions
and I made our wishes known to Lt. Greely. He kindly assisted and tonight favored us
with some interesting remarks on the Polar question: a subject absorbing to us at
present. An Aurora observed at 8p.m.


## Thursday Dec 15th 1881

The party are exercising by banking up magnetic observatory. My shoulder is
very painful; sleep is almost an impossibility. Frederick the other Esquimaux has
exhibited the desire to follow the example of Jens. In a melodramatic manner he
flourished a huge wooden cross in one hand and with the other on his heart bade us
all “good bye” intimating that he was tired of life and about to immolate himself on
the Shrine of the Polar Question. We dissuaded him however.
Temperature Max -27.4° F Min -46.2° F

( Copy of Christmas dinner menu)

## Friday Dec 16th 1881

Deep sea temperature observed at norm today. Surface 28.9, at depth 33 ft. -28.7
Thermometer observed and (?) -38.4 — -46.5


## Saturday Dec 17th 1881

The party are exercising by banking up the magnetic observatory. An Aural
streamer observed. Range of the observed and corrected from -38.2 to 46.2


## Sunday Dec 18th 1881

Israel commenced taking magnetic observations the usual monthly lasting
three days , today. Usual Bible reading in the morning. Ther. Obs. And Cor. Ranged
from -40.2 to 46.7
