---
title: "1881-09-08:1881-09-15"
subtitle: |
  Making it back home.
date: 2024-04-13T05:00
categories: [diary, rice, camp]
editor_options:
  chunk_output_type: console
order: 8
---

## Thursday, September 8, 1881 

Started on our journey again 7 a.m. It is unnecessary to describe my
suffering. Although the distance to St. Patrick's Bay was short we were tramping
until 10 p.m. before we reached the valley above the bay. I could hardly move. The
Dr. preceded me as we neared the camping place and succeeded in finding water
before I arrived. I laid down on the ground and he erected the camp over me. I could
not move. He was compelled to leave me and start for camp.

## Friday, September 9th, 1881 

The Dr. reached the station home at 3 a.m. and on reporting our condition a
party made preparations to go to my assistance. Out of a large number of volunteers
five were considered a sufficient number. They were preceded by Sgt. Brainard who
reached me at 10 a.m. He brought with him a bottle of wine, warm rolls and soon
prepared for me a good cup of chocolate. Although I had fasted so long I had no 
appetite. The wine however was very pleasant as I suffered much from thirst. At 12
p.m. the four men who followed Brainard arrived. They had brought a litter or ladder
which served as one. I was placed on it and carried about four miles where the
mountain afforded an easier ascent. The ascent was very steep and rough and an
ineffectual attempt to carry me up decided Sgt. Brainard in sending for more help.
Bender started for camp and five volunteers at once started. Meantime the first party
were doing all they could for my comfort. An alcohol lamp was kept burning in the
shelter tent which they had again erected over me again. Their own discomfort was
considerable. The thermometer was below zero and they were compelled to walk to
and fro to keep warm. The tent was too small to afford them shelter. I could not
move hand or foot. At 8:30 p.m. the additional party arrived and with much difficulty
they succeeded in carrying me up the hill where they placed me on a sledge and
hauled me to the station where we arrived at 2 a.m. Sept 10th.

## Saturday, September 10, 1881

After being placed in bed this morning I began to improve. I had before
leaving rested in sleeping bag in my tent but Gardiner had kindly arranged a cot for
me in the quarters. The relief party who brought me in here, very much exhausted.
Whistler (sic) had his foot frozen. I have learned that Lt. Lockwood found on
arriving at station that his foot was badly frozen the day we met him as we started out
Aug 29th.


## Sunday, September 11, 1881

Lt. Lockwood and Gardiner accompanied by the Esquimaux Frederich with
dog sledge started to explore the Bellot Valley. Sunday service in the morning — Rum
issued in the evening.

I learn that during my absence ten, 10, muskoxen were killed at the “Bellows”
about 13 miles from station. A sled and wagon abandoned by the English Expdn of
‘75 were also found. Also the open water encouraged Lt. Greely to send party under
Sgt. Brainard to Cape Beechy with whale boat to establish a depot of provisions to be
used by sledge parties traveling north this fall. They encountered great difficulties.
The moving ice continually threatened to crush the boat.

## Monday September 12, 1881

Sgt. Brainard’s party however, succeeded in reaching Cape Beechy after
fifteen tiresome and dangerous hours at the oars. They found it impossible to return
with the boat as the ice closed up the passage completely. They returned by land.
They started from Station 31st August and returned Sept 3rd. Today Brainard and
Cross make a trip to Hogback. They use snowshoes. I am improving rapidly


## Tuesday September 13, 1881

The carpenters are busily engaged in finishing the ceiling of quarters.
Lt. Lockwood and Gardiner return at 8:30 p.m.


## Wednesday, September 14, 1881

The weather continues fine. The inner walls of quarters completed today.

## Thursday September 15, 1881

Dr. Pavy and Whistler with Eskimo Jens and two sledges and teams start out
to examine Archers Fiord and English caches supposed to be in that direction. They
had only proceeded a short distance on the ice when a pack of nineteen wolves were
seen on the ice. Several nimrods attempted to get near enough for a shot but the
wolves were too wary and left the ice, following the ravine to the northward.
Whistler came back for a rifle and ammunition. The strong force of wolves rather
alarmed the Dr.
