---
title: "1882-01-21:1882-01-31"
subtitle: |
  Daylight approaches.
date: 2024-06-22T20:20
categories: [diary, rice]
editor_options:
  chunk_output_type: console
order: 22
---

## Saturday January 21st 1882

Pendulum observations continued. Several fine displays of aurora were seen
especially one of curtain formation—color white at some times. It was so bright as to
throw shadows from objects on the ice. I attempted to photograph it but did not
succeed in getting any impression on the plate. Temp Obs. and Cor. -34.1 to -43.7°F



## Sunday January 22nd 1882

Our usual Sunday services; day spent in the ordinary way; more sleeping than
during the week. Temp. obs. and Corrected -40.7 to -46.1



## Monday January 23rd 1882

Quite a diversity of phenomena today. A radiant meteor exploded about 7:30
a.m; a lunar halo was observed and a few auroral streaks faintly showed up.


## Tuesday January 24th 1882

No pendulum observations as the day and night were cloudy. Temp.ramged
from -39.2 to 49.3 observed and corrected.
“New England rum was so thick at 6 p.m. today that it was a difficult matter to
puncture it. Temp -46.4. Lunar halo observed at 6 pm. Biederbeck’s birthday—
celebrated in the regulation style. Lt. Lockwood makes some remedies in addition to
those he favored us with some time since. As a lecturer he has not improved.

## Jan 26

“Deep sea temperatures taken”

## Jan 27

“Israel while observing at the astronomical observatory had the misfortune of
freezing his foot.”


## Jan 28

“Daylight is approaching fast. Two lunar halos were observed during day


## Jan 29

“Our usual Sabbath observances in the morning. Lt Kislingbury walked to
Cape Murchison and not having informed anyone of his intention caused considerable
anxiety by his long absence. A relief party met him near the Station. He reported the
tent down at Murchison.”

Two dogs — one eloped with “the queen of one of the other dogs. They came back
looking much more for their honeymoon.” This incident “caused some amusement.”


## Jan 30

“Bar falling indicating storm. Snow began to fall and continued all day.
I walked to Dutch Island with Lt. Kislingbury. I sorted and arranged our library and
varnished some negatives. Min -52.7, Max 33.6 Mean -39.12

## Tuesday January 31st 1882

Biederbeck looking over the hospital stores found all the hospital brandy
frozen solid. One or two bottles had broken. By tasting some of the frozen spirit we
were accused of being “hard drinkers”. I hauled some ice with Jens and the dog team.
I had considerable amusement from the pups—Askhim’s—antics in the team. We are
breaking him in and he does not take kindly to work! But the old (?) dragged him
along and he soon found it easier to travel on his legs than on his back. Temp. Obs.
and corrected Min. 44.2, Max. -31.1, Mean -38.37.
