---
title: "1881-11-01:1881-11-07"
subtitle: |
  Expeditions with not enough gear.
date: 2024-06-10T21:50
categories: [diary, rice, expeditions]
editor_options:
  chunk_output_type: console
order: 13
---

## Tuesday, Nov 1, 1881

Remarkable deposit of hoar frost noticed by the observers. Sufficient was
collected in gages to measure .05 of an inch. This measurement however includes all
that has fallen since last snowstorm but most of it fell this morning. I assisted Israel
in ascertaining the deep sea temperature.

Preparations going on all day for the attempt to cross over the Strait to Polaris
Harbor and “Halls Rest.” The men are exhibiting considerable ingenuity in fitting
themselves out. Our supply of clothing and paraphernalia for field work in this
climate is sadly deficient of much that is necessary. For foot gear especially we are
badly off. The cork soled arctics are much to heavy to walk in, Esquimaux boots we
have next to none and those few we have too small. There are not enough of the
buckskin moccasins to go around. I have not received a pair as they were issued
while I was out in the field. Dr. Pavy generally fits me out from his private store of
Esquimaux boots which is extensive.

By evening Lt. Lockwood and his party of seven men completed their
preparations packed their sledges with the provisions etc and pulled it out to Distant
Cape so as to allow a start in the morning free of the sledge encumbrance...

They returned at 5 p.m. An unusual dinner was prepared by order of Lt. Greely in
honor, I presume, of Lt. L’s departure on his hazardous attempt.

## Wednesday Nov 2nd 1881

Lt. Lockwood and party started this morning for Cape Beechy from which
point they propose to pass over to Polaris Bay. The load on sledge, an English one
formed here, weighed 1,100 — a heavy drag through the snow and over the icefoot.

I followed at 9:30 with dog sledge and Jens the Esquimaux. The plan is that I
am to support Lt. Lockwood, aiding him with the dog team until the arrival of Dr.
Pavy when I join him for a trip to Wrangle Bay to carry rations for the spring trip.
My team was composed of but 7 dogs as two of the bitches had newly born litters and
not the same number of serviceable dogs, 7, were left for the Dr. The load of 600 lbs
that we had on the sled was therefore too heavy. I met with the Dr. and Lt.
Kislingbury near Dutch Island and arranged with him to leave one bag of bread at
Murchisons to be brought on by his team as he expected to have a light load.
Overtook the party of Lt. Lockwood at Murchison at 2 p.m. They were plodding
along steadily and expected to reach Beechy by night. I furnished them with a drink
of chocolate I had brought warm in our sleeping bag and proceeding on advance. I
reached Cape Beechy at 7 p.m. and Lt. L and party at 8 p.m. We occupied the
snowhouse erected some time ago and were very comfortable I brought but one
sleeping bag as it reduced the weight on the sled and Jens the Eskimo and I occupied
it.

## Thursday November 3rd, 1881

Slept comfortably last night. Jens and I filled the
sleeping bag so that the warmth of our bodies was confined and kept us warm.
Temperatures during the night -17.


Lt. Lockwood started out with Jens and the dogs for Cape Murchison to bring two
bags of coal. He also intended to examine the small boat left in St. Patrick’s Bay by
the English in 1875. I, assisted by Ellis, put out rations and built a snow pedestal for
a telescope we had brought. Brainard with rest of party started back for remainder of
their load abandoned the night before. Brainard and party returns at 1:30 p.m. Lt. K
returns at 4 p.m. He forgot to bring sack of pemmican which was to be part of his
load. Mock moons observed at 8 p.m. Temperature -11.


## Friday November 4, 1881

Lt. Lockwood sent me for the boat at St. Patrick’s Bay. Started with dogs and
sledge. Returned with boat at 3 p.m. During my absence Lt. L and party made
attempt to cross the Straits. They took whale boat which made their load so
cumbersome that it was impossible to advance over the rough ice. They consequently
returned after a few hours. Lt. L proposes making another attempt with the smaller
boat brought from St. P Bay. Dr. Pavy and Lt. K arrived at snowhouse at 6 p.m.
They made but slow progress being 12 hours from home station. Dr. is on his way to
Wrangle Bay with more rations to be used in the spring campaign. I shall accompany
him with the other dog team.

## November 5th 188]

I observed an amusing tableau last night before retiring. The snow house not
being large enough to accommodate us all, Ellis Saler and Biederbeck pitched a tent
outside and occupied a sleeping bag large enough to hold three men. Ellis and Saler
retired and left the candle burning for Biederbeck who was making preparations for
cooking breakfast in the morning. I happen to look in the tent and was almost
convulsed with laughter to see “Old Mate”, one of the most disagreeable and mangy
looking of all the dogs, occupying the middle place in the sleeping bag left vacant for
B. He was lying on his side head on the pillow with one paw thrown lovingly over
Ellis’ neck. As I laughed he looked up and expression said as plainly as I can
interpret it: “It is all right. I am one of them.” At 9:30 Dr. Pavy and I started for
Wrangle Bay. Lt. Kislingbury accompanied him with one sledge and team and Jens
and I had the other one.

When we left Lt. Lockwood and party were making preparations for crossing the
Strait. They are repairing the boat I had brought from Murchison

We proceeded for a short distance when Jens told me that the little bitch
“Gypsy” exhibited symptoms of matemity. He tried to drive her back thinking she
would return to the snow house but she returned to the team. We then proceeded with
her. She soon became tired an ill and we carried her on the sledge. This reduced
our teams to six dogs each as three bitches were left at the home station with litters.
We had a difficult time traveling over much ground which was also icy. Camped at
7:15 p.m. in the valley.

## Sunday November 6th 1881

During the night Gypsy managed to enter the tent and while we were at
breakfast gave birth to two pups. After breakfast Jens and I built a small snow house
and placed the mother with the pups in it. I left some pemmican so that she would
not starve during our absence. We then broke camp and deserted her. 9:30 am. We
traveled all day and had a most interesting journey. We found the traveling very
good. At about noon we entered the lower ravine leading in a more easterly direction
towards Wrangle Bay.

(Drs’ sled) was on a much lower level than the one we were on and we made a most
exciting descent into it. Finding our efforts to hold the sledge back to no avail I threw
myself on the sledge. Jens dragged by the standards behind. The dogs started on the
full run and would not be controlled; the sledge however descended faster than they
and running away some rocks the lines became entangled and the sledge stopped.
Found good traveling in the lower valley and reached our destination Wrangle Bay at
2:30 p.m. It was then beginning to snow.


## Monday November 7 1881

Added our load of rations to the depot already established and started to return
at 1:30 p.m. and after a successful trip arrived at Snowhouse at 10 p.m. Learned by a
note left by Lt. Lockwood that he had returned home having failed.
