---
title: "1881-09-01:1881-09-07"
subtitle: |
  On having the flu (rheumatism) while out.
date: 2024-04-13T04:00
categories: [diary, rice, rheumatism]
editor_options:
  chunk_output_type: console
order: 7
---

## Thursday, September 1st, 1881

The ravine at the foot at which we camped appeared to afford us a means of
reaching the mountain top above and traveling overland to Wrangel Bay. Broke
camp at 1:30 a.m. and made the difficult ascent to the top of the mountain. Our
progress was slow and difficult. Aneroid Bar. indicated height of cliffs 2,500 feet.
We found a strong breeze blowing with drifting snow. Our progress was now most
difficult. The temperature was a few degrees below zero, the wind blew fiercely
sending the blinding snow into our faces. Our breaths condensed and froze on our
beards until the weight of the ice pulling the hair was painful. It was impossible to
stop to eat or rest as no shelter was afforded. Reached Wrangel Bay at midnight and
the first warm meal. We had traveled twelve hours and had eaten nothing but two
biscuits each. We suffered very much of thirst and found that eating the frosty snow
gave but little relief.

The pleasure it gave us to find water in our camp at Wrangel Bay can only be
imagined. We had to cut through a foot of ice to reach it. Found traces of muskoxen
at Wrangel Bay.

## Friday, September 2, 1881

Left camp at 11:30 a.m. The temperature during the night was low. Our boots
were frozen stiff and in placing a small canteen of rum to my lips it stuck instantly to
them and in removing it the skin was taken off in places. Our socks generally got wet
during the day and we would place one pair between our shirts at night where they
were dry by the heat of the body. We now took to the icefoot and experienced much
difficulty in places where the heavy ice has crowed and piled on the shore. I
attempted to pass on new ice that had been formed during probably, our [] thaw two
nights. I fell through in one place and got wet up to my waist. My boots were filled
with water. I emptied them and rung the water out of my socks.” The boots retained
so much of the water that I had wet feet all of the rest of the day. We reached Cape
Frederick VII at 9 p.m. were forced to follow the shore of Lincoln Bay arrived to the
north side where the depot of rations was placed. Through a mistake we pass them
and finding ourselves out of the bay concluded to proceed a little further to Cape
Union instead of doing so the following day as we had intended. The distance was
greater than we supposed and by the time we were able to get back to Lincoln Bay
after reaching Cape Union it was 10 a.m. on the 3rd. I was the first to find the depot
and after a walk of 22 1/2 continuous hours with nothing to eat but a cup of chocolate
and two biscuits, the cache of provisions was a pleasant sight.

We, notwithstanding our fatigue spent a few hours looking over the
provisions. We went into camp at 1 p.m. of 3rd.
We spent the day in examining the provisions, 1000 rations were left by the
English and we found them after a lapse of six years in general good conditions. The
bread was all spoiled as the barrels had shrunk and water had entered, but chocolate,
preserved meat, stearine, etc. were as good apparently as when deposited. The barrel
of rum was two thirds full. Some of the tobacco tea and sugar was injured, but the
greatest part was still good.

I was extremely lame all day, my feet and joints of the legs swollen, but did
not (know) the true cause of it until later. I suffered it the simple stiffness from the
long walk and exposure, but the acute rheumatism had attacked me. I made every
effort to overcome the difficulty as I attended to the stiffness induced by long
traveling without rest but I found to be impossible, however, at 6 p.m. we started.
Our progress was very slow as I suffered excruciatingly at every step. We had not
traveled far before we met a large Arctic hare which I succeeded in shooting with the
revolver I carried. It was a beautiful animal with its fur as white as snow, the tips of
the ears black. The Dr., with a naturalist's enthusiasm proceeded at once to add it to 
his load although I attempted to dissuade him on account of the already oppressive
weight of our loads. I could not think of adding more to mine.

## September 5, 1881

After leaving the depot at Lincoln Bay yesterday evening we crossed the bay,
on reaching the other side the Dr. followed the icefoot while I kept out on the ice in
bay. The Dr. had the best traveling and had to wait until I caught up to him. We then
plotted along for sixteen hours reaching Wrangel Bay at 10 a.m. today. We pitched
our tent and attempted to get water from the brook that supplied us when traveling the
other way, but the frost had dried it up and we were compelled to melt snow. I cannot
discuss my suffering in reaching this point. The acute rheumatism attacking my legs
and arms made every step extremely painful to me. As the malady is always
accompanied by fever I felt parched and thirst all the time, and water was a scarce as
in the desert of the Sahara. I was cruelly disappointed several times after cutting 18
inches of ice to what I supposed was a pool of fresh water in the ice foot to find the
water either salt or dried up.

At 6 p.m. we started again. I was so sick I had to be helped to my feet and could walk
but slowly. The rheumatism had attacked my body so that breathing was difficult and
painful. Reached Cape Beechey and camped at lakes 3 p.m. of 6th.

## Tuesday September 6, 1881

Started again at 9 p.m. I was suffering terribly. Dr. Pavy found my pulse up to
114. I desired that the Dr. to leave me and go on in advance so that I might rest my
terribly swollen legs and follow him as soon as I could. He would not hear of such an
arrangement. He then transferred almost all of my load to his pack leaving me only
the tent to carry. After going a short distance he concluded to abandon the rabbit and
other supplies articles such as cartridges, etc. Our progress was necessarily slow. The
rheumatism in the muscle of the chest caused me to groan with every respiration. My
limbs were terribly pained also —. Nothing but the greatest exercise of will enabled
me to move at all. On several occasions thought of giving up let the consequences be
what they might. We reached the small cache of provisions we had left in the ravine
between Beechy and St. Patrick’s Bay at 9 a.m. on the 7th. We prepared a meal and
quenched our thirst. Erected our shelter tent and attempted to rest but the pain
racking my limbs made sleep impossible.

## Wednesday, September 7, 1881

At 8 p.m. we attempted to start, but it was an impossibility with me. Dr. P
tried to encourage me to get as far as St. Patrick’s Bay so that he could get from there
to Station and send a party out for me. I was as sensible of the importance of
proceeding as he was but for me to move was absolutely impossible. We made a
compromise, however. I promised him to start the following morning. If it was still
impossible he was to proceed to the home station and return with or send out party for
me.

