---
title: "1881-07-21:1881-07-28"
subtitle: |
  Leaving Disco
date: 2024-03-02T02:00
categories: [greenland, rice, diary]
editor_options:
  chunk_output_type: console
bibliography: refs.bib
---

## 1881-07-21

Left Disco at 2 a.m. and, after a run of about sixty miles along the coast of Disco Island, arrived at Rittentank.
We were welcomed by a salute of three guns from the battery in front of the governor's residence.
Mr. Clay came on board looking none the worse for his winter in the arctic.
Lieut Lockwood, with a small party, visited the "loomery", seven miles from here, and brought back seventy birds, principally the small auk. 
He reports great numbers of birds.
A great many were shot that could not be picked up on account of their inaccessible position on the high cliffs.
Many eggs were destroyed by the birds dragging them off in their fall from their nests on the shelving rocks.

We have taken seven dogs in addition to those already procured.
Also, about two tons of the dried fish for food.
Dr. Parry and H. Clay are busy getting their effects on board.

## 1881-07-22

Left Rittentank this p.m. for Upernavik.
Will pass through the Waigett, the strait separating Disco Island from the mainland.

## 1881-07-23

On the water.
Still in the Waigett.
The scenery through this strait is most magnificent.
The land is within sight most of the way.
The frowning cliffs rise abruptly from the sea, which, calmed by the numerous icebergs, is as placid as the waters of Central Park, and reflects back the cliffs and the snow clad mountains behind them.
The stately bergs present the most beautiful feature of the panorama.
Immense islands of ice, pure and white as Parlan marble awaiting the chisel fo the sculptor, although no artist could give them forms more beautiful or fantastic.
They resemble at times the mosques and minarets of some oriental city, when the midnight sun dyes them in glorious tins.
The base is generally marked with a beautiful green where the dark sea water washes over it.

## 1881-07-24

Arrived at Upernavik this morning at 5:30.
The latitude of this place is 72&deg; 48' north.
It resembles the other Danish settlements we have visited:
Consists of the residence of the Governor, the storehouse, cooper's shop, smithy, and the turf huts of the Esquimaux population.
Governor Elberg has received us very graciously, and expresses his willingness to aid the expedition all he can.
The Inspector of North Greenland, whom we saw at Disco, is here temporarily on his tour of inspection.
We shall take on more dogs here also skins and skin clothing.

## 1881-07-25

It is blowing hard this morning and a party that was to leave for Proven did not start.
The dogs have been landed on a small rock near the harbor, that they may get some exercise.
Expect to be here about five days.

## 1881-07-26

A party -- Lieut. Lockwood, Gov. Elberg, Cross, Linn, and myself, -- started this morning for Proven to procure two Esquimaux to accompany the expedition as dog drivers and hunters.
The distance is about fifty miles.
We took the usual passage through the islands, as the sea was too rough to go outside.
Our conveyance was the little steam launch, "Lady Greely".
The scenery in the channels and fiords through which we passes was most remarkable and on the same grand and impressive scale as that of the Waigett.
Some of the passages were so narrow that, at first sight, it appeared impossible to get through them; but nearer approach proved them to be as deep as mid ocean.
The walls of the adamantine cliffs descend perpendicularly to a great depth.
Nothing but rock, evidently of volcanic origin, appears.
Occasionally a little carpeting of beautiful green moss covers the avidences of nature's convulsions, and t is the only representative of the vegetable kingdom that we can see.
We arrived at Proven at 9:30 p.m.

## 1881-07-27

At Proven better opportunity for studying the habits of the aborigines is afforded than at any other place we have visited.
The whalers and exploring parties seldom get there; so the influence of the white man is less perceptible.
They retain their habits of life as practiced before the Dane improved their condition, to a greater extent than in other parts of Greenland.
I spent at least three hours in one of the most uninviting igloos or huts that I saw.
The manufacture of a cap of eider down, for which I was waiting, gave me pretext for so long a stay.
The hut was built of turf, rocks, and moss and was entered through a long tunnel so low that I was compelled to crawl on my hands and feet to effect an entrance, a most disagreeable and humiliating proceeding, as the dogs and the natives (the latter not much better than the former in point of cleanliness,) enter by the same way.
On reaching the small interior hole, which is at once the living, eating and sleeping room, I was surprised to see the mistress of the house in a state of almost complete nudity, sitting on the shelf or platform on which they sleep.
I turned aside to give her an opportunity of donning a more complete costume, but a furtive glance soon showed me that she appeared to prefer being dresses as nearly *a la* Venus as possible.

I at once faced the music and had soon made a satisfactory arrangement by which I was to receive a cap in exchange for a neckerchief I wore.
The cap was not *in esse*, so the contract remained executory until it was completed.

The maker measured the dome of my intellect with great pleasure, and was soon engaged in cutting up eider skins and fitting them into the form of a cap.
Her scantiness of clothes appeared to give her an advantage as she seemed to get along more expeditiously by odling the material between her feet while sewing.

The room was very low, and the atmosphere stifling and nauseating from the odors of the skins and oil.
There was no glass in the window.
As a substitute they used the the membraneous tissue tissue of the stomach of the seal, which, when oiled, is almost transparent.
There was no stove nor fireplace.
Instead, they used a hollow stone for a lamp with fuel of oil and moss for a wick.
The floor was of stone and earth.
The sleeping arrangements were very simple.
A platform extending six fee from the wall occupies one side of the room.
This is the receptacle of skins and furs during the day, and, when the natives retire the make it a general couch; each disciple of Morpheus drawing over himself or herself, so many of the skins as are necessary for comfort.

The costume of the Esquimaux women is so nearly like that of the men that, at first sight, it is not easy to distinguish the sexes.
The articles of attire of the women, however, are made up in a much more elaborate manner than are those of the men, showing more ornamentation.
The feet are encased in dainty boots reaching above the knee.
Next come the pants or trunks, which are very short, coming down not more than half the length of the thigh, the boots being pulled up to meet them.
The upper part of the body is covered in a cassock of seal skin, devoid of buttons and pulled on over the head, or allowed to fall back at the shoulders at pleasure.

My cap being complete, I was glad to get away from the nauseating surrounding and breathe the fresh air again.
Many of the natives, however, occupy much better dwellings than the one I have described.
Such a one represents the habitations of the poorer class, who have not intermixed with the Danes.
In the evening I entered a larger building occupied by a half breed, and, finding an old violin on the wall, I soon had a number of the fair sex dancing enthusiastically to my rather imperfect music.
I became very popular with them at once, and, in leaving Proven, which did at 10:30 p.m., a bevy of dark maidens were at the shore to bid me Goodby or the Esquimaux equivalent.
Through the efforts of Gov. Elberg, the two Esquimaux Christiansen and Edwards, were induced to accompany us.
The exhibited considerable emotion, proving themselves very unlike their stoical North American (Indian) relatives.
On parting with their friends, the shed bitter tears, that fell indeed until their homes were out of sight.

We had a very pleasant passage returning.
The midnight sun made it light as day.
We shot one hundred and thirty looms, or, at least, we recovered that many; large numbers remaining dead on the cliffs inaccessible to us.
The females were sitting in rows, incubating, and, when shot, the eggs would roll off, and come crashing down the rocks in thousands, turning the water yellow.
The two natives were in their element, darting about in their graceful kyaks, picking up the dead birds.

## 1881-07-28

We arrived at Upernavik, reaching the ship at about 10:30 a.m. Took dogs on board the Proteus.
Their number is now thirty-four grown, and three pups.
I am busy the remaining part of the day photographing the Inspector and the Governor's children, and in getting my things packed away before starting to sea again.
 
