---
title: "1881-07-24:1881-07-31"
subtitle: |
  More provisioning.
date: 2024-04-11T02:00
categories: [diary, rice, greenland]
editor_options:
  chunk_output_type: console
order: 3
---

## Sunday July 24th, 1881

Left Disco this morning at 2 a.m. and after a run of about sixty miles along the
coast of Disco islands arrived in Rittenbank an were welcomed by a salute of three
guns from the battery in front of the governors residence. Mr. Clay came aboard
looking worse the wear for his months in the arctic. Lt. Lockwood with a small party
visited the loonery seven miles from here and brought back 70 birds, principally the
small Auk. He reports great numbers of birds and a great many were shot that could
not be picked up on account of their inaccessible position on the high cliffs. A great
many eggs were destroyed by the birds dragging them off in their fall from their nests
on the shelving rocks.

We have taken seven dogs in addition to those already procured. Also, about two tons
of the dried fish for food Dr. Pavy and H. Clay are busy getting their effects on board.
Arrived at Upernavik this morning at 5:30. The Latitude of this place is 72
48° W. it resembles the other Danish settlements we have visited. Consists of the
residence of the Governor, the storehouse, Coopers shop, Smithy and the Inuit huts of
the Esquimaux population. Gen. Elberg has received us very graciously and
expressed his willingness to aid the expedition all he can. The Inspectors of North
Greenland when we were at Disco is also here temporarily on his tour of inspection.
We shall take on more dogs here, also skins and skin clothing.


## Monday July 25,1881

It is storming hard today and a party that was to leave for Provan did not start.
The dogs have been landed on a small rock near the harbor that they may get some
exercise— Expect to leave here about five days.

## Tuesday July 26, 1881

A party (Lt. Lockwood, Gov. Elberg of U, Cross, Linn and myself) started this
morning for Proven to procure two Esquimaux to accompany the expedition as dog
drivers and hunters. The distance is about 50 miles. We took the inside passage
through the islands as the sea was too rough to go outside. Our conveyance was the
little steam launch “Lady Greely”. The scenery in the channels and fiords through
which we passed was most remarkable and in the same grand and impressive scale as
that of the Waigtt . Some of the passages were so narrow that at first sight it
appeared impossible to get through them. But a nearer approach proved them to be as
deep as mid ocean; the walls of the adamantine cliffs descend perpendicular to a great
depth. Nothing but rock appears and that is evidently of volcanic formation.
Occasionally a little carpeting of beautiful green moss covers the evidence of nature’s
convulsions and is the only representative of the vegetable kingdom that we can see.
We are at Proven at 9:30 p.m.

## Wednesday, July 27, 1881

At  Proven a better opportunity for studying the habits of the primitive
aborigines, is afforded than at any other place we have visited. The whalers and the
exploring parties seldom get there so the influence of the white man is less
perceptible. They retain their habits of life as practiced before the white man
improved their condition in other parts of Greenland. I spent at least three hours in
one of the most uninviting (gloots?) or huts I saw. The manufacture of a cap of eider
down for which I was waiting gave me a pretext for the long stay. The hut was built
of (?) rocks and moss and was entered of a long tunnel so low that I was compelled
to crawl on my hands and feet to affect an entrance, a most disagreeable and
humiliating proceeding as the dogs and natives, not much better than the former in
point of cleanliness, enter in the same way. On reaching the small interior hole,
which is at once their living quarters, eating and sleeping room, I was surprised to see
the mistress of the housed in a state of almost complete nudity sitting on the shelf or
platform on which they sleep. I turned aside to give her an opportunity of donning
more complete costume, but a furtive backward glance soon showed me that she appeared to prefer
being dressed as nearly A la (?) as possible. I at once face the music and had some
made a satisfactory arrangement by which I was to receive a ice cap in exchange for a
neckerchief I wore. The former, however was not in issue so the contract remained
executory (sic) until it was completed.

The maker measured the dome of my intended with great precision and was
intensely employed in cutting up Eider skin and fitting them with a cap. Her
scantiness of clothes appeared to give her an advantage as she seemed to get along
more expeditiously by holding the skin between her feet while sewing.

The room was very low and the atmosphere stifling and nauseating from the
odors exhaled by the skins and oil — no glass in the windows, as a substitute they used
the membranous tissue of the stomach of the seal which when oiled is almost
transparent. There was no stove or fireplace instead they used a hollow stone for a
lamp with fuel oil and moss for a wick. The floor was of stone and earth. The
sleeping arrangements were very simple, a platform about two feet high extending from the wall and
occupies one side of the room. This is the receptacle of skins and (?) during the day
and when the natives retire they make a (?) couch each disciple of morphea drawing
over him or herself as many of the skins as necessary for comfort. The costume of the
Esquimaux women is so nearly like that of the Inuit that at first sight is not easy to
distinguish the (?) although the former make theirs up in a much more elaborate
manner(-----------------) Their feet are encased in a pair of dainty boots
reaching - (?) at the knee, next came the pants or trunks which however are very short
coming down, not more than half way of the thighs. The parts arte pulled up to meet
them. The upper part of the body is covered by a cassock of sealskin devoid of
buttons and pulled on over the head. An attached hood can be drawn over the head or
allowed to fall back on the shoulders at pleasure. My cap being complete, I was glad
to get away from the nauseating surroundings and into the fresh air again. Many of
the natives from here occupy much better dwellings than the one I have described. -
such as one represents the habitations of the poorer class who have not ..... with the
Danes. In the (?) I entered a large building occupied by a half
(missing sentence) need and finding an old violin on the wall I soon had a
number of the fair sex dancing enthusiastically to my rather imperfect music. I
became very popular with them at once and in leaving Proven which we did at 10:30
p.m. a bevy of dark maidens were at the shore to bid me ‘goodby’ or their Esquimaux
equivalent. Through the efforts of Gov. Elberg the two Esquimaux, Christiansen and
Edwards were induced to accompany us. They exhibited considerable emotion
prying themselves away unlike their stoic North American relatives. On parting with
their friends they shed bitter tears that fell indeed until their homes were out of sight.

We had a very pleasant passage returning. The Midnight Sun making it light
as day. We shot 130 loons or at least we recorded that many. Large numbers
remaining dead on the cliffs inaccessible to us. The females were sitting in rows
incubating and when shot the eggs would roll off and come crashing down the rocks
in thousands turning the water yellow. The two natives were in their element darting
about in their graceful kayaks picking up the dead birds.

## Thursday July 28, 1881

We arrived in Upernavik reaching (?) at about 10:30 a.m. Found Proteus
about ready to start. Took dogs on board, their number 11 now increased to thirty
from former and three pups. I am busy the remaining part of the day in photographing
the inspector, the Gov’s children and in getting my things packed away before
starting to sea again.


## Friday, July 29, 1881

We left Upernavik today at 4:30 p.m. All hands were busy in writing letters
before starting to go by the Danish ship which was soon to leave Greenland for
Copenhagen. I sent letter to Herald.

Inspector and Gov. Elberg came and bade us farewell not leaving the ship
until we had passed out of the harbor. I made photographs at Provan.


## Saturday, July 30, 1881

We found very little ice. It has been the experience of almost all Arctic
voyages to fall in with the pack after leaving Upernavik. Our departure from
Upernavik furnished us with material for reflection. It is the last point at which the
least semblance of civilization can be found — the course now leads into that vague
unknown region which is so indefinitely marked out to be undefined. Our ship now
ploughs waters that have seldom been disturbed. No sails whiten the broad expanse
of dark blue water. In their stead the stately bergs stalk majestically along. We can
scarcely refrain from descanting in the beauties of the latter whenever the subject is
suggested. To think of them only as miniature islands of ice conveys no idea of their
remarkable beauty — when lighted up by the peculiar rays of the midnight sun. I shall
refer to them again later.

## July 30, 1881

Today when in Latitude 74° 30’N considerable excitement was occasioned by
the discovery of a veritable Polar bear. We had steamed into a small pack of ice
extending in a narrow inlet and his bearship was seen on one of the pieces of ice
enjoying an evening meal of a seal he had caught. A bear! A bear! was shouted in
excited tones all over the ship and soon our hunters were seen emerging with their
rifles. The bear a few hundred yards from the ship and among a number of shots fired,
one or two bullets hit him. — up to this time he had been perfectly indifferent to our
approach not finding it disagreeable for him. He went in to the water and swam a
distance emerging to crawl in the ice again — by this time Kislingbury and Lockwood
with Mr. Clay rowed nearer to him and soon dispatched him, bringing him
triumphantly aboard. He was soon enthusiastically hoisted on board and as soon as he
could be placed in position I proceeded to make a photograph of him. It was a young male in good condition. Our two Esquimaux were in their element dressing the carcass and soon had it hanging.


## Sunday July 31, 1881

We are making very good progress North though it is considered strange that
no large packs of ice have been met. We fell in today with a small pack. Several seals
of the “square flipper” kind were seen on the ice and we succeeded in shooting one I
also photographed it. The bear meat which we had for breakfast proved quite
palatable although a little fishy, but the ducks rather reconciled us to that taste and the
bear was not more fishy than they. Our fare will be still more varied by the meat of
the seal which is considered excellent.
