---
title: "1882-01-11:1882-01-20"
subtitle: |
  A storm hits the camp.
date: 2024-06-16T16:20
categories: [diary, rice]
editor_options:
  chunk_output_type: console
order: 21
---

## Wednesday January 11th 1882

Weather still continuing cold. Lt. Greely favors us with a lecture on “The
Poles” which | did not have the pleasure of hearing as I was assisting Israel at the
observatory.

He has so much trouble and difficulty in manipulating the instruments and freezing
his fingers that I thought I might save him some of it by sending the signals of time
over the telephone for him. I was not of much service however. Israel’s work is very
hard in adjusting the transit, he inadvertently froze his nose against the frosty
instrument. While we were there the temp stood -45. Temp during day ranged from -
30.8 to 52.9 observed and corrected.


## Thursday January 12th 1882

Ellison’s birthday. An excellent bill of fare for dinner. Temperature from 31.4
to 36.9 obs. and cor.


## Friday January 13th 1882

Clear weather. Ther. ranged from -37.0 to -53.2


## Saturday January 14th 1882

Light snow fell during day. Began falling at 10:40 a.m.
Max temp 36.1, min -56.4. Obs & Corrected. No pendulum observations taken on
account of the stars being observed.

## Sunday January 15th 1882

Light snow falling till 6:30 p.m. Maximum temperature -26. Min. 37.1


## Monday January 16th 1882

Today we experienced the most severe storm I have ever witnessed.
Barometer began to fall a little after midnight, 15th, a light breeze setting in from the
west at that time. Sky clouded up at this time a small space at the zenith only being
partly clear so that a few stars could be seen shining through. Barometer showing
more decided fall as the morning advanced. At 8 a.m. slight fall of snow began wind
sprang up from SW, blowing 4 miles an hour. The remarkable fall of barometer
induced Lt. Greely to have it observed every 15 minutes. About now the expected storm came in full
force, Ralston who was on duty found great difficulty in reaching the instrument
shelter when the violence of the wind blew out his candle. He returned and Jewell
accompanied him. They succeeded in reading the thermometer of -12° 5 a remarkable
rise of 17 ° 8 since 7 a.m. Brainard read the tide gauge. By the time 1 o’clock came
round the storm had so increased in violence that although several relays and relief
parties attempted to reach the instrument shelter none were successful. Connell and]
started for the tide gauge but had not struggled through the blinding drift before our
lantern was extinguished and we were compelled to return to the Station. I cannot describe
the fury of the storm. It was intensely dark, the wind was howling out of the N.E. at
the rate of 60 miles an hour carrying with it clouds of frozen snow that cut the face
like powdered glass or sparks of fire. The resistance to the body was tremendous, it
was impossible to move in an upright position. We lost the path and tumbled over the
hill to the ice foot making no attempt to save ourselves. On returning two volunteers
joined us and we started again with a red signal lamp. It was Brainard and Biederbeck
who accompanied us, their success at 12 o’clock causing them to (?) our attempt. We
all stumbled precariously over the bank but could not find the path. We crawled along
a short distance when someone behind me said “Let’s try and get back.” Biederbeck’s
red light showed up a little in advance however and we followed it and succeeded by
mere chance in reaching the snow house over the tide gauge. Our return was not quite
so difficult but we had hard work and returned to the quarters bruised and almost
frozen. Our faces were covered with a sheet of ice. Observations were now
discontinued at the shelter and a thermometer was exposed at the side of our building
near the door. At 2:30 p.m. the anemometer cups were blown away. Several tents
were blown down and other damage done. The highest velocity recorded before the
anemometer blew away was 65 miles but there is not doubt it increased afterwards
and we are inclined to think 80 miles per hour not too high an estimate. It was during
a lull just before 12 o’clock that the winds shifted around to N.E. where it remained
during the remainder of the storm. It ceased to blow with great violence after 4
o’clock but a stiff breeze was felt all day as soon as the observation at the instrument
shelter and the tidal gauge resumed. Life lines were placed for the guidance of the
observer.

Temp -11° .0 to -31°.1 obs. and corrected


## Tuesday Jan 17th 1882

Snow ended at 3:30 am: clouds cleared away at 6am. Jewell observed the
temp of water and thickness of ice today. The working party engaged all day ia
repairing the damage of yesterday’s storm. Several tents had to be re-erected: the
commissary pile covered up, etc. I again went on duty observing. Temp from -22°.6
to -40.7 obs. and corrected.


## Wednesday Jan 18th 1882

This morning we were smoked out at an early hour by the pipe of our stove
choking up. Our heating arrangements are very poor, a good deal of gas is (?) and we
breathe much more of it than is compatible with health, especially as we have to
spend so much time indoors during the long and cold arctic night. As I note this the
sooty comets are falling on me and my surroundings. (see further remarks in private
journal)

Temps -31.9 to -47.1

## Thursday January 19th 1882

The period for monthly magnetic observations has come around and as Israel
is still engaged with the pendulum Ralston and Jewell will make the magnetic obs.
leaving the regular meteorological work to Henry and I. I find it very tiresome and
tedious work—hourly observations, 8 hours on and 8 off. Routine work never suited
me.

An auroral arch was observed at 7:35 and strong magnetic disturbances
disappeared at 8:30 and another brilliant arch flashed out at 10:30 but disappeared
instantly. -34.1 to -43.7 Obs. & Corrected. Gardiner’s 25th birthday. High tide 89
inches.


## Friday January 20th 1882

Pendulum observations continued. Israe] sticks very faithfully to the work
which is very difficult. Some New England rum supposed to be 10 above proof was
exposed when I went on duty at midnight and 1 made the following observations
regarding the effect of the low temperatures on it. At 2 a.m. a thin coating of slush
formed on it—temp -41.7, at 3. slush 1/2 inch in thickness at -44 temp. I again
examined it at 5 a.m. and found that it had thickened to the bottom of the vessel
resembling somewhat snow saturated with water. Our highest tide was observed
today 8 feet 6 inches. The highest observed by the Discovery while here was between
6 and 9 feet. Temp obs. and cor. -31.8 to -47.4
Cross’ birthday.
