---
title: "1881-10-14:1881-10-31"
subtitle: |
  The disappearing sun, auroras, and coal.
date: 2024-05-19T17:00
categories: [diary, rice, camp]
editor_options:
  chunk_output_type: console
order: 12
---

## Friday October 14, 1881

Weather fair, a Solar halo was observed between 10 a.m. and 11:30 a.m.
The sun has condescended to shine for such a short time each day for a long time.
Today Lt. Greely somewhat startled us by announcing that today was the last on
which we would see the sun ‘till at least the 29th of February. We all rushed out door
and sure enough Old Sol only exhibited himself for a few moments and then set in a
glorious glow of colors. The refraction of its rays presented a beautiful effect in the
horizon for some time after. Ther. ranged from maximum -10 to minimum -27.4.


## Saturday October 15, 1881

Weather fair. Two mock moons -----appeared at 5:30 p.m. and disappeared at
ll p.m. They displayed vertical rays of light.
Temp. from -10 to -27.4


## Sunday, October 16, 1881

Weather fair. “Deep sea temperature (taken every fifth day) was again taken
today. Nineteen and one half new inches of new ice had formed since the last hole
was cut in ice. An aurora observed at 7 p.m. lasting about 20 minutes. It was
perfectly white.
Very low temperature (Max -18 Min -32)

## Monday October 17, 1881

Cloudy weather, cleared up at 3 p.m.
Temp. Max.-10 Min. -29



## Tuesday October 18, 1881

Clear weather. Sergeant Linn, Connell and Henry started for the coal mine a
Watercourse Bay to get out coals. They returned at 3 p.m. They found no difficulty
in tumbling down several tons of coals. On their way over to the mine they found the
ice cavern or grotto mentioned in Sir Geo Nares’ work.
(Max -11 Min -33.9) Cool


## Wednesday October 19, 1881

Weather clear, partly cloudy during latter part of day. I started with Jens the
Eskimo and a team of nine dogs to take a load from the mine to Cape Murchison a
pleasant dog drive. I arrived home at 3:45. Getting quite dark at that time. At 9 p.m.
an aurora was observed. Several meteors seen, the most remarkable by Israel at 9 pm.
Ther. From -16 to -29

## Thursday October 26th, 1881

The darkness is increasing rapidly. We are compelled to use artificial light
almost all the twenty four in the quarters. Jupiter plainly visible at 2:30 p.m. Connell
took coal from Watercourse Bay to Cape Murchison. Weather warm. -2 to -23


## Friday October 21st, 1881

Dr. Pavy left station at 9:30 a.m. for the coal mine, returning at 2:30 p.m. with
430 lb coal. Jupiter, Arctivas Capella , and Alpha Gemminium were plainly seen at
mid day. A new experience to see stars plainly shining at noon. (Max +4 Min -15)

## Saturday October 22, 1881

Sun ended at 12:30 a.m. Following stars visible at 1 p.m.; Marc Polans,
Vega, Capelle, Castor, Prelix, and Cygni. Jupiter and Arcturus are now visible during
the twenty four hours. An aurora was observed; the magnometer during the display
was ----disturbed. Temperature from (+7 -20)


## Sunday Oct 23, 1881

Lockwood accompanied by Sgt. Brainard, and Pvt. Connell started for Cape
Beechy. They took Eskimo Frederick and one dog team. They are to build
snowhouse at Cape Beechy for the accommodation of the sledging parties in the
spring. Ther. Maximum +7 to Minimum -20.

Usual Sunday services as follows; reading the Bible and prayer for the absent
and singing sacred and otherwise during the evening.

## Monday October 24th, 1881

Another load of coals from Watercourse Bay to Murchison Sgt Gardiner.
Temp from -2 to -15.9


## Tuesday Oct 25th, 1881

At 9:30 a Solar halo appeared ---above the horizon, color pink. This halo as
determined by it’s position and altitude was 23° above the sun. Maximum +7.
Minimum -10.


## Wednesday Oct 26th, 1881

Pvt. Ellis made another coal trip. Lt. Lockwood and party return from Cape
Beechy at 4:10 p.m. They succeeded in building a snow house which by two nights’
occupation proved to be comfortable. The weather continues comparatively warm
today from +8 to -10 was the temperature.

## Thursday Oct 27th, 1881

We were busy for an hour or two building an ice wall around the house. We
have been furnished with a few hours exercise every morning in constructing this
wall which will afford a shelter from the north wind. I have the honor of being
appointed Superintendent of Construction. The temperature still continues mild.
Maximum +2° F to Minimum -12° F


## Friday Oct 28th, 1881

Added another tier to the ice wall. Snyder and Biederbeck while taking a
constitutional walk in the evening were somewhat startled by hearing a wolf howling.
It was so dark they could not see him but distinctly heard his footsteps in the snow.
They were about a mile from the station but did not tarry. I’m prepared to certify that
O’Leary’s best time was beaten. Thermometer, Max. +5, Minimum -10.

## Saturday Oct 29, 1881

It is now getting quite dark during the day at midday. Polaris was Plainly
visible. Several displays of aurora were observed in the evening.

## Sunday Oct 30th, 1881

It is now fourteen days since the sun disappeared below the horizon and to test
the power of active rays still existing in the faint light reflected from sun at noon I
propose to attempt another photograph. Israel, Whistler started after breakfast and
took the direction of Distant Cape. We hauled photographic apparatus on Hudson
Bay Sledges.

I exposed dry-plate for about one hour about noon. Sun must have been 6° or
8° below horizon. Amused ourselves while plate was exposed—target practice with
rifle Whistler had brought along. Our Sunday evenings are generally spent in
singing. Lt. Kislingbury, Gardiner, Ellis & Schneider taking prominent parts. Their
repertior (sic) consists of old songs and older hymns. I sometimes assist with the
violin.

Usual quart of ram dispensed. Said rum is not a particularly delectable article
of spirits tasting more like diluted commercial alcohol than anything else. For the
first month or more we used the English rum deposited by the Nares expedition at
Cape Hawkes and appropriated by us. Our own ‘New England’ is a poor substitute.


## Monday Oct 31st, 1881

Weather clear. Sgt. Ralston & Pvt. Henry made a trip to the summit of Bellot
I. to read Max and Min thermometers. Max recorded since Sept 30 21.05 Min -33.8
All hands making preparations for an attempt to cross the Straits under Lt. Lockwood.
