---
title: "1882-01-01:1882-01-10"
subtitle: |
  Travels to read instruments, and the pendulum is completed.
date: 2024-06-16T16:15
categories: [diary, rice]
editor_options:
  chunk_output_type: console
order: 20
---

## Sunday January 1st 1882

This is my first opportunity of setting down the new '82. Jewell and Lynn
started for Mount Campbell the highest point on Bellot Island to read the anemometer
and thermometer placed there. After several hours search they returned without
finding them.

At 4 p.m. we sat down to our excellent New Years dinner—the turkey. The
temperature comparatively warm -21.1 to -29.1. Most of the party enjoyed a siesta
during the day as they were somewhat exhausted from watching the Old Year out and
New one in.


## Monday January 2nd 1882

Two mockmoons observed at 1:25 p.m. accompanied with lunar halo and
aroral arches. All disappeared at 4 p.m.
Temp still warm -21.1 and -26.6 obs. and corrected


## Monday January 3rd 1882

Brainard and I started for Bellot Island. We were gone five hours. Found the
instruments and made the observations. Traveled on snow shoes most of the way.
Temp today from -24.6 to -36.2 obs and corrected.

We found them on Mt. Campbell read only -20 showing a warmer strata at that
elevation. This was my first walk from Station since my accident.

## Wednesday January 4th 1882

The arrangements for taking pendulum observations are now all complete.
Israel is awaiting clear weather so that astronomical observations for time can be
taken. Hourly watches to continue through twenty four hours announced today. The
true time is recorded at which the tide rises or falls an inch. Lt.
Lockwood lectures in the evening on “Sledging.” His remarks were principally
quotations from the accounts of former arctic explorers and must have cost him
considerable labor and research. Temp -25.5 to -33.6. I did not state result of
anemometer reading on Bellot Island by myself and B. Velocity of wind since Dec 1st
4,210 miles.



## Thursday January 5th 1882

Tide gauge observations continued. Two mockmoons were observed. Temp. -26.8 to 37.6 obs. and corrected.


## Friday January 6th 1882

Israel commenced surveying the pendulum today assisted by Connell who ran
the chronograph for him. Temp -34.1 to 42.2 obs. And cor.

## Saturday January 7th 1882

Pendulum observations continued. Temp -28.2 to -33.6. Obs. And Cor.


## Sunday January 8th 1882

Our usual Sabbath. Bible reading by Lt. G. in the moming; the remainder of
the day very quiet until 7 p.m. when the ration of rum is issued after which
conversation flows fast and furious. This New England rum of ours appears to contain
more volubility and eloquence to the square yard than any stimulant hitherto
administered. An argument can be readily started on any topic on Sunday evening.
Temp observed and corrected -28.2 to -49.2.

The sun light at noon is gradually growing brighter. Lt. Kislingbury could
read the time indicated by his watch by it today.


## Monday January 9th 1882

Today experienced the coldest temperature yet observed by us. The ther.
ranged from -44.0 to -56.4 obs. and corrected.


## Tuesday January 10th 1882

A still lower temperature from -47.2 to -57.2. obs. And corrected. Israel in
taking signal observations at astronomical observatory, froze his toe.
