---
title: "1881-07-07:1881-07-16"
subtitle: |
  Leaving Newfoundland
date: 2024-03-01
categories: [diary, rice, greenland]
editor_options:
  chunk_output_type: console
---

## 1881-07-07

For our transportation to Lady Franklin Bay the United States government has chartered the sealing steamer Proteus, owned and hailing from St. John's, Newfoundland.
She is commanded by Capt. Pike, who has for his first officer, Mr. Norman; second, Mr. White. 
Mr. McPherson is first engineer, and Mr. Carmicheal, second.
The crew is composed of sturdy Newfoundland sailors.
Capt. Pike and his mates have all had long experience in ice navigation, and the ship is specially adapted for her mission, as she was built for the seal fishing, and everything that experience could suggest was done to make capable of resisting the action of ice.

This morning the freight for the expedition, that arrived per Hibernian, was brought on board the Proteus and every preparation made for a start.
At noon Captain Pike gave the order to get under weigh.
About 12:30 we move from the anchorage, and amid cheers and the waving of handkerchiefs from the shore steam slowly through the narrows. 
Much interest is taken in our departure and it is with feelings of regret that we gave for the last time for many days upon that most interesting feature of society and civilized life represented by a group of gaily dressed ladies who stood on Signal Hill and kindly waved us "good by".
Bleak and cold as Newfoundland looks, with its drapery of fog hanging over its high cliffs, we shall exchange it for the lands of eternal snow with regret.

Our start is a favorable one and we go coasting along the shore under both sail and steam at a rapid rate.
The wind is a pleasant breeze and we are soon carried past the entrance to the great bays, Conception and Trinity.
The crew are busily engaged cleaning up the decks and "making things ship shape" as the mate says.
Our party occupied their time in locating, doffing their city costumes, and donning clothes more substantial and better adapted for ship life.
Some are evidently meditating on the future fo the arduous undertaking toward which we have taken the initial step today and which has probably, in many cases, never been so seriously considered as at this moment.
I realize that we have left behind us relatives, friends, society, civilization and every thing that makes life pleasant on this terren sphere, for the long space of two years, is enough to furnish ample food for reflection even to the most thoughtless.
And then, it is impossible to avoid looking forward with something like apprehension to the future sojourn in those regions of perpetual snow and ice under a hostile sky.

No matter how much forethought may have been exercised thse thoughts have never so strongly suggested themselves as at this time when we find ourselves on the broad Atlantic with the prow of our ship pointed toward the north star and every revolution of the propeller speeding us nearer our inhospitable destination and further from home and friends.
We retire at a late hour to be lulled to sleep by the motion of the ship, which has not yet become unpleasant, and dream of icebergs and polar bears.

## 1881-07-08

We are bowling along at a splendid rate.
The weather is fair but the temperature is growing much cooler.
Now that we are all together a roll call to make acquaintance is not amiss:

We are members of an Arctic exploring expedition sent out under the auspices of the War Department of the United States of America (or, more immediately, of the Chief Signal Officer, U.S.A.) "for scientific observation in the Arctic regions."
The plan of the expedition is to establish a station at Lady Franklin Bay, latitude 81, 40 and spend two years in observation and exploration, making journeys by sledge to the north at such times and seasons as practicable.
The expedition is under the command of Lieut. A. W. Greely, and the following are the names of the persons comprising the party: Lieut A.W. Greely, in command; Lieut Kislingbury; Israel, astronomer; Gardiner, astronomer, Jewell, meteorologist; Ralston, meteorologist; Rice, photographer.

## 1881-07-09

There is a strong breeze from the north-west which makes our progress very slow.
The temperature is getting very much cooler.

## 1881-07-10

Our first Sunday at sea: A pleasant day. The wind has changed and is now in our favor, wafting us along, with the aid of steam, at a splendid rate.

## 1881-07-11

At four p.m. wind hauled ahead, increasing in force until it now threatens to become a gale.
No observation has been made.

## 1881-07-12

The wind is still adverse.
The temperature has fallen very low and indicates the presence of ice.
At 8 p.m. we fall in with the ice, a long narrow strip of field ice, through which we carefully steam at half speed, following the tortuous channel which the opening in the ice affords.

The crow's nest has been hoisted up to the fore-top-gallant-mast head, and in it the second mate stands and directs the movements of the ship. 
The presence of the ice has calmed the sea, and we are surrounded with a most beautiful scene.
The blue-green edges of the ice, blending with the dark blue ocean an lighted up by the oblique rays of the setting sun, present a panorama of rate beauty, resembling a mosaic on a grand scale.

In the foreground can be seen several seals of the harp species.
Lieut. Kislingbury hazards several shots at them but without effect; the distance is too great.
Occasionally a mammoth whale may be seen emerging, like some miniature island among the ice, to blow, sending a spout of water, which, dyed with the tints of the setting sun, presents all the colors of the rainbow.
Our position can only be ascertained by dead reckoning as no meridian observation has been made.
We place this floe of ice in latitude 61&deg; north.

## 1881-07-13

Our party, or those have been so unfortunate as to be sea sick, are now recovering their spirits in this water, kept smooth by the ice.
This *mal de mer* has visited our party pretty generally, without regard to age or station. 
I am so fortunate as always to enjoy an immunity from it.
Lieut. Greely has experienced the unpleasant effects in a large degree.

We fall in with another ice pack in about latitude 63&deg;.
It presents the same appearance as the former pack we met.
The wind blowing off it makes the temperature very cold, making us realize that we must expect to invade Boress' chilly heath earlier than we anticipated.

[*missing*] winds have been from the north, which augurs well for our success, as the ice will be driven out of Smith Sound, admitting our passing through it.
Today we sighted land for the first time since leaving St. John's.

## 1881-07-14

We have been out one week today.
The sea is calm.
A dense fog hangs over everything.
We are compelled to go at half speed for fear of encountering bergs, which cannot be recognized at any distance through the hazy fog.
The captain proudly relates an instance of the ability of the good Proteus: Which out on a sealing voyage she had just extricated herself from a pack and had attained about the rate of half speed, when, before it could be avoided, she ran head on to a large berg.
She actually ran several feet up the side of the berg, so great had been the momentum.
She however, sustained no other injury than the destruction of her head gear and the breaking off of the outwater. 
Such anecdotes of her prowess naturally inspire me with much confidence.
The fog lifts about one p.m. giving us another glimpse of the snow clad mountains, nestling along the seacoast.

## 1881-07-15

We can occasionally see the land when the fog lifts.
The captain and Mr. Israel both were successful in getting meridian observations.
Our latitude is 66&deg;, 42' N.
Land well in sight, I recognized the land very readily from my recollection of last year's cruise.
To a stranger from the south the weird appearance of these latitudes is most remarkable and fascinating.
A dark, bold, striking coastline beyond which the snow clad mountains, ascending to dizzy attitudes, can be seen as the gauzy curtain of fog lifts.
The sea, dotted with bergs, presents no other obstruction to the eye; and, as we again turn our eyes to land, we are impressed with the desolate and silent appearance of everything.
No sign of animal or vegetable life disturbs or beautifies the scene.
Silence reigns supreme.

## 1881-07-16

The fog has again settled down this morning, and as we are supposed to be in the vicinity of Disco, the speed is lessened.
We are, it is reckoned, very near Godhaven at 2 p.m., and the engines are stopped, as it is useless to attempt to make the land, owing to the dense fog which still prevails.

At eight p.m., to our great delight, the fog, like some huge curtain, rolled back, showing the snow clad island of Disco close by.
As the fog dispersed, it presented a most beautiful sight.
The dark coast, plentifully dotted with glistening bergs, the high land covered with snow, an occasional stream of ice water trickling its way, like some silver ribbon, over the ice and rocks to the sea below, and the fog, like a halo, draping the highest peaks.
But as we drew nearer, no sign of sunny summer could be seen, except a few patches of hardy grass struggling to grow in favored spots, and, in the valleys, the beautiful green velvety moss which gives to this land of desolation its name.

I instantly recognized the conformation of the land from my recollection of my trip in the Gulnare last year, and was able to direct the way to the harbor of Godhaven, which we soon reached, dropping anchor at about ten p.m.
The sun was still up and the little basin-like harbor looked very peaceful and inviting as we [*not clear*] into it.
It was calm and still as a pond, and, in the glassy water, which was as clear as crystal, was reflected the frowning, towering cliffs which surround it.

The picturesque Esquimaux, in their funny costumes, were soon gliding over the water toward us in their graceful, fairy like kyaks, while the pantalooned maidens were tripping down the rocks to get a nearer view of us.
It is all so novel and charming that those of us who have not been here before cannot repress the greatest interest and curiosity in surroundings so strange and so unlike the civilization we have left.

Dr. Parry and Henry Clay, who were expected to join us here, are at Rittentank, distant about seventy miles.
We will leave here in a few days for that place, and will thence proceed to Upernavik, our last stopping place until our destination is reached.
From information Inspector Smith gives us, we infer that our chances for getting through the ice this year are very good.
The winter in Greenland has been a very mild one and reports from the northern stations say that navigation is not impeded by ice.
