---
title: "1881-09-24:1881-10-05"
subtitle: |
  Setting up more depots.
date: 2024-04-14T07:00
categories: [diary, rice, camp]
editor_options:
  chunk_output_type: console
order: 10
---

## Saturday, September 24, 1881

Lt. Lockwood started with four men to convey the rations left by Brainard in
St. Patrick’s Bay to Cape Beechey. I sent my photographic kit with instructions for
him to leave it at Watercourse Bay.


## Sunday, September 25, 1881

After breakfast, Cross and I start for Watercourse Bay. We travel by the
icefoot, finding the camera, etc. near the picturesque bergs referred to above. I
exposed six plates on the best subjects and left the apparatus to be brought in by the
returning party with the sledge. We come back overland getting into camp at 2 p.m.

## Monday 26, 1881

I started this morning accompanied by Jens the Esquimaux with sledge and
team of dogs ten to convey additional stores to depot “B” Cape Beechy. My load
consisted of pemmican and extract of beef. I had much difficulty until passed Cape
Murchison. I was compelled to unload the sled several times and carry it over rough
places. Several of the dogs fell into the water. It is difficult to understand how a sled
can be pulled through or over the rough ice front we traveled. Nothing but a
Greenland sledge, lashed together with walrus hide could stand the terrible strain
twisting we gave it; and no native power on earth other than a team of Eskimo dogs
could have dragged it. I found excellent traveling from Cape Murchison to Beechy
where I arrived at 3 p.m. After a jaunt of nine hours. I found Lt. Lockwood and
party in camp occupying the tent that had been erected by Brainard and his party
when the whaleboat was abandoned. As the tent was completely filled by the party,
Jens and I were compelled to sleep outside the tent with no shelter. Of course we
were in sleeping bags but the cold from the ground made our rest very uncomfortable.
We gave the dogs a meal of pemmican before turning in. They kept up a continual
wrangle all night — proving that they were not much fatigued. I therefore determined
to make an early start to return during the night - -10 rather cold for sleeping out.



## Tuesday, September 27, 1881

I started to return at 5:30 a.m. It was then threatening snow. Did not attempt
to cook any breakfast as the party in the tent had not arisen. I therefore kept on until
Cape Murchison was reached when I stopped about an hour making chocolate and
warming feet. Found icefoot changed by tide around Distant Cape and was
compelled to make new road. Arrived at home 1:30 p.m. Learned that the day before
a large male wolf had been shot near our quarters. Although gaunt and thin it
weighed 81lbs and was five foot from nose to tail. Lt. Kislingbury shot him. Wolf
stood 33 1/2 inches hind quarters and 33 inches fore. Today Connell and a companion
brought in another that had been poisoned. Lt. Lockwood returned at 8 p.m. He and
party were well run down. It snowed slightly today.


## Wednesday, September 28, 1881

A party of three went to Watercourse Bay and looked into the condition of the
muskox meat left there It was all right. They brought each a small piece home with
them.

## Thursday, September 29, 1881

The weather very fine today. First serenade of the season and intended for
sleepy Israel and myself. All the musical, or rather noise making instruments brought
into requisition. Dr. Pavy and Whistler preparing for the northern journey.


## Friday, September 30, 1881

Will the music never cease? The xylophone has experienced but little rest
since it has been unpacked. Dr. Pavy prevented from starting by threatening storm. I
however photographed the outfit, banners and bunting flying from both sledges.
Connell after breakfast, and Lt. K after dinner started out after wolves. Both returned
without success. The two natives astonished with an electric shock from the
Chronograph. The “Regulars” happy, as the dead horse, in other words, the advance
pay, worked off. Carpenters and tinsmith at work on the bathtub.

I developed the plates but find the dull weather and attempts to catch the ever
moving dogs makes the negatives wanting in detail.



## Saturday, October 1, 1881

The weather looked threatening. Dr. Pavy and Whistler postpone trip.


## Sunday October 2, 1881

Today Dr. Pavy, Whistler and Eskimo Jens started Cape Joseph Henry. Their
object is to take provisions to be used when an attempt is made in the spring to reach
our most northerly point.


## Monday October 3, 1881

Fair weather today. A most remarkable change in temperature in one day, the
thermometer ranged from +12 to -15.


## Tuesday, October 4th, 1881

A Solar halo appeared at 9 a.m. and continued until 3 p.m.
At 7 p.m. a mock moon (?) was observed. It contained the prismatic colors.
Temperature today -5 to 17.9

## Wednesday October 5, 1881

At 8:45a.m. Brainard, Bender and I started for the Bellows near the head of
Discovery Harbor. We took with us the new Hudson Bay sledge just completed by
Cross. We loaded it with tent, cooking utensils and provisions. I also took along
camera and plates with the intention of getting if possible a view of "The Bellows".
The weight of our load was 143 lbs. We reached "The Bellows", distant from camp
16 miles, at 3:40 p.m. A strong breeze was blowing and the temperature very cold.
Before we could get tent pitched Brainard had his nose and one cheek frozen. Bender
and I escaped from being frostbitten by rubbing the face almost continually. I set the
minimum thermometer I brought along and at 7 p.m. it read -15.
After preparing some chocolate over a spirit lamp we crawled into a sleeping bag.
Spent a miserable night. Expected to find some rubber blankets supposed to be left at
the Bellows by the party that had been there in September, but found they had been
taken away, so nothing between the snowy ground and the sleeping bag. It was
therefore extremely cold for that portion of our bodies nearest the ground.
