---
title: "1881-12-19:1881-12-31"
subtitle: |
  Christmas and the New Year approach.
date: 2024-06-16T16:10
categories: [diary, rice]
editor_options:
  chunk_output_type: console
order: 19
---

## Monday Dec 19th 1881

Began reading new tide gauge, and Gardiner up for first time today.


The heavens were filled with auroral displays all day too numerous and varied to
describe, but some appearances very beautiful. Ther. from -41.2 to -49.7. Obs and
corrected.

## Tuesday Dec 20th 1881

Two meteors were observed falling today, one of them exhibiting a beautiful
rosy colour. A faint aurora was also seen.-40.2 to -46.7° F was the range of standard
thermometer observed and corrected.


## Wednesday Dec 21st 1881

My shoulder is very painful. I think it is much more seriously injured than
appears in examination which can only be superficial. Today is Brainard’s birthday
and his bill of fare furnishes us with a splendid table for dinner. Deep sea temp. taken
by Henry. Standard thermometer read from -40 to -46.7 today observed and
corrected, correction is -3.8


## Thursday Dec 22, 1881

Weather much warmer, light snow began to fall at 11 a.m. Temp ranged from
-26.6 to -28.8. obs and cor. Many jokes were made about the warm weather. One or
two of the party seriously observing that the day was uncomfortably sultry.


## Friday Dec 23, 1881

Snow continues. Weather still warm -23.3 —28.1
Cross is going around with a badly swollen cheek the effect of toothache.

## Saturday Dec 24th 1881

Salor’s birthday, occurring today was celebrated by the usual gastronomical
preparations for an extra dinner. Snow ceased falling at 3 p.m.
It being Xmas eve the presents kindly sent by some thoughtful parties in the
States were distributed by our commander amid much chaffing and sport. The
kindness of the donors was highly appreciated. The interest attending the opening of
the mysterious packages was very great. I found myself the possessor of a pipe
accompanied by a neat chamois skin bag filled with fine tobacco. I have no way of (?)
the use of the articles however and find the (?) to me, property something of an
elephant.

A handsome lap-robe intended for Ryan who returned on the “Proteus”, was
raffled for and although I came within one of winning Ellison was the happy man.
Egg nog was passed around and drunk to the health of loved ones at home but we
were compelled to admit that the same exhilarating beverage imbibed by our friends
was superior to ours. The eggs which were preserved and rather mummy-fied.
We have managed to arrange a programme for Monday night which will require but
little preparation. Temp. obs and cor -33.6

## Sunday December 25th 1881

Light snow fell part of the day. Weather cloudy remainder. A very quite
Christmas. Lt Greely read a chapter from the Scripture as usual on Sundays. Our
dinner was the main feature of the day. A copy of the bill of Fare can be seen on a
page previous to this. Considerable sleeping indulged in as we all feel rather fatigued
after last nights dancing. In the evening an extra quantity of the (?) in the form of
New England rum was issued the exhilarating effect of which added to the pleasure of
looking over the fine illustrations in some London Graphics of a late date enabled us
to pass a very enjoyable evening. It was impossible however to prevent our minds
from wandering over snow and ice to the homes of friends and loved ones so vividly
brought before us by the season of Christmastide. We think there was not one of our
small party who did not indulge in a retrospective view of the events and
surroundings of our last Xmas. Ther. Obs and cor. Ranged from -24 to 39.9.


## Monday, December 26th 1881

Temperature stationary. -22.6 to -26.6, obs. And cor. After midnight last
night all hands being up and no disposition of retiring appearing a dance was
proposed. It met with such favor and was kept up till morning. Schneider and his
violin furnishing the music. I was unable to assist him as usual owing to the state of
my arm. There was much hilarity and no sleep secured, so after breakfast everything
became quiet, nothing occurring to break the silence but the regular snoring of one of
the sleepers. In the evening our entertainment came off a programme of which will be
here inserted.



## Tuesday Dec 27, 1881

Sea temperature observed today. Surface 29.1 and at a depth of 33 feet 28.8
Thermometer obs. And cor., Max. 27.1, min. 37.4


## Wednesday, December 28th 1881

Weather clear. Temp. from 32.1 to 44.2


## Thursday, December 29th 1881

Lt. Greely lectures on “war memories” — an interesting narrative of some of
his personal experiences at Fredericksburg. Thermometer ranged from -36.1 to 45.2
obs & cor.


## Friday Dec 30th 1881
“Nothing noteworthy” -32.4 to 46.7 was the range of temperature.


## Saturday Dec 31st 1881

A cool but pleasant day. The evening was given over to Bacchus and
Terpsichore. I removed my arm from the bandages and attempted to relieve Schneider
in furnishing music for the dancers but found the positions of holding the violin a
painful one for my shoulder. Temperature from -34.1 to -46.2
