---
title: "1881-12-01:1881-12-09"
subtitle: |
  Fetching ice and building a pendulum.
date: 2024-06-15T16:40
categories: [diary, rice]
editor_options:
  chunk_output_type: console
order: 17
---

## Thursday December 1st 1881

I took up the duty of making the hourly observations again at midnight. The
most difficult part of the tour is that leading to the tidal gauge. We are compelled to
descend the steep bank to the ice foot and notwithstanding the quantity of ashes
sprinkled in the path it is slippery and unsafe. I’ve had several severe falls, the heavy
cork sole shoes adding to the uncertainty of the footing. Ralston has demolished
several of Bender’s tin candle lanterns by falling on them. We have accused him of
tobogganing on them after the style of the Montreal club. The weather is becoming
warmer.

## Friday Dec 2nd 1881

Temperature increasing. Weather fair. I did not state that Sgts. Ralston and
Brainard visited Mt. Campbell on Bellot Island for the purpose of reading the
anemometer and thermometer placed there permanently. The anemometer has
registered 657 miles since it was first placed in position on Oct 9th. Thermometer
showed minimum temp since Oct 31st to have been -38°0. Temperature of water and
thickness of ice in harbor: temp air -27, surface of water -29.1
Depth of 33 ft. 29°.2 Thickness of ice 33”
Snow began falling at 11:35 a.m. ending at 5:30 p.m


## Saturday Dec 3rd 1881

Weather clear except a short time at midday. Jewell is on duty again. Gardiner
is getting along very nice and hauled ice in morning. Frederick the Eskimo has for
some time appeared disheartened and has been making me the confidant of his
gloomy prospects, such as that of running away. Some days since Jens acted in the
same manner but we reassured them of their safety and security. They have both been
treated with the greatest kindness by all the party but as there has been little for them
to do for some time past they have become lonesome and homesick and doubtless
imagine all manner of things. As Frederick appeared to be very much in earnest today
I sat up at night to intercept any attempt on his part to escape.



## Sunday Dec 4th 1881

Two beautiful mock moons at midnight which lasted until 8 a.m. They
exhibited the prismatic colors. At 4 a.m. contact arches were formed. The mock
moons were about 22° from the real. An almost complete circle surrounded the moon
passing through the mock moons.(diagram)


## Monday Dec 5th 1881

Weather cold. Front put in the icehouse over pendulum. I exercised myself,
dogs and Jens in hauling ice.

A beautiful Lunar halo with mock moons was observed at 6 p.m.

The most interesting occurrence of the day was the lunar eclipse of the moon which
commenced about 10 a.m. and lasted for over an hour. It was almost a total eclipse
and the moon during the time exhibited different colors. An auroral streamer was
observed. (diagram)


## Tuesday Dec 6th 1881

Weather clear. I exercised by hauling ice as usual. Some members of the party
still engaged in the pendulum building.

## Wednesday Dec 7th 1881

Nothing of importance occurred to vary the monotony of our everyday or
night life. The usual exercise taken by the party is walking, hauling ice, working in
the pendulum shelter. This work lasts for an hour or two each day. The hauling of ice
falls to me and I shall be loath to give it up as it furnishes me with healthful exercise
much more exhilarating and beneficial than mere walking on account of the activity
required in following the sledge and assisting the Esquimaux in managing the dogs.
Weather fair. Lunar halo observed.


## Thursday Dec 8th 1881

Weather clear. Biederbeck went to Distant Cape for Hudson Bay sledge left
there by Jewell some time since. Nothing noteworthy occurred.


## Friday Dec 9th 1881

Weather fair. Sky clear. Pendulum building completed today.
