---
title: "1882-02-09:1882-02-22"
subtitle: |
  Hunting hares.
date: 2024-06-22T20:40
categories: [diary, rice]
editor_options:
  chunk_output_type: console
order: 24
---

## Thursday February 9th 1882

The light steadily increasing and has suggested the coming field work. Lt.
Greely therefore inaugurates the preparation for it by setting Bender to work making
spirit lamps and cooking utensils. Fredericks our saddler is set to work experimenting
with foot gear. This is rendered necessary by our almost total destitution of anything
suitable for traveling on the sledge journeys that are contemplated. After much
discussion and cussin’ they decide on a combination of canvas and blanket (see
private journal). Biederbeck is rolling piles of wire. Beautiful effect of land of polar
Clouds. Lt. Greely favors us with a lecture on “Storms”. Temp. Max. -47.1 min. -
54.8, Mean -50.60



## Friday February 10th 1882

Nothing noteworthy occurs. The extreme low temperature ceases to Provoke
any comments. Temp for 24 hours today was -50°.below zero, Max. -51.1, Min.-54.1,
Mean -52.40


## Saturday February 11th 1882

At 2 a.m. I happened to be awake and the observer on duty informed me that
the thermometer corrected —stood (at) —Sixty -60°1. Difference of temperature
between inside and out over 110° ! I spent the day in experimenting with some
lamps—finding the shortest time in which they would melt ice, etc.

## Sunday February 12th 1882

Our usual Sabbath—distinguished from the other days of the week by Bible
readings in the morning and rum at night. The latter infuses a little harmless hilarity
which finds vent in some chorus singing and violin music.

The weather still continues cold. (See private journal this date)


## Monday February 13th 1882

A very busy day—the coldest also. Lt. Lockwood, Ralston and Brainard went
to Bellot Island to read the meteorological instruments left there. I tested some nine of
Bender’s spirit lamp and got satisfactory results from some of the them. About the
time Lt. Lockwood and the party were expected back I started out with Frederick and
the dog team to meet them. Missed them as they took a new route back.

Lt. Greely has been experimenting to discover the rapidity with which sound
travels in this country. I assisted him by discharging firearms at a distance of a mile
and a half mile from him. He noted the flash and catches the sound, recording the
same with aid of chronograph. 1 mile 4 1/2 sec: 1/2 mile 2 1/4.


In the evening Lt. Greely conversed with me in regard to my going out on
sledge trips in the spring. He was good enough to say I could have command of party
supporting Lt. Lockwood—an important mission in his estimation. The Dr. has for
some time expressed a strong wish to have me accompany him and I am more
desirous of going North on this side than of following the Greenland coast on the
other. I think the chances of attaining the highest latitude are greater, I so expressed
myself and Lt. Greely kindly allowed me to choose.

For particulars—private journal this date. I spent the evening in reading Hayes the
most charming writer of arctic literature I have yet read.


## Tuesday February 14th 1882

St. Valentine’s day: probably the most remarkable anniversary of the day that
any of us experienced. Our mail did not arrive: so our love missives and caricatures
did not arrive in time to awaken our affections or wound our vanity. I hauled ice and
experimented further with sound.

## Wednesday February 15th 1882

More experiments with the shotgun and chronograph. The results of our
experiments will not, I fear, throw much light on the science of acoustics.

In using the guns at this low temperature we have found that all the oil must
be removed from all parts of them as it freezes and will not allow the weapon to
work.

One of our Nimrods was greatly chagrined to find on drawing bead on 4
hare—that the trigger could not be pulled. The hare walked leisurely off while he was
frantically trying to get his gun off.

Jens shoots a hare. It is a much larger animal than I supposed: in fact I believe
that the hares are larger than the foxes in this part of the world.

In the eve I was out with Dr. Pavy and Lt. Kislingbury (see private journal). I hauled
ice with Jens and the dogs during the day. Weather still cold.

## Thursday February 16th 1882

Brainard and Cross go to Bellot Island and hare-hunting: but do not bag any.
Frederick the Esquimaux has better luck bringing back a fine specimen. After Jens
and I our usual quantities of ice, he, Jens, emulates Frederick’s example and returns
with a duplicate hare. Hare stew in prospective. The light is daily increasing: the cold
weather still continues however.


## Friday February 17th 1882

I make some further experiments with some new tinware of Jakay’s. I note
time required to melt ice, boil the water, raise same in upper tin to given temperature,
etc. I also note the amt alcohol used. The results were generally satisfactory. I
hauled ice as usual; in fact I would dislike to give up this 2 hours exercise with the
dog teams. It is both exhilarating and healthful. The dogs are a never failing source of
interest to me. The more one uses them the better does he appreciate their usefulness
and intelligence. I am getting so I can use the whip quite effectively: and succeed in
communicating the strange sounding words with which the Esquimaux guide them—
with some degree of resemblance to Jens. I still, however, elicit a provoking smile
from the superior “whip.”


## Saturday February 18th 1882

Brainard yesterday ascertained that 2,200 lbs of the musk oxen meat still
remains. This is agreeable intelligence as the meat is excellent and while it lasts we
will laugh at scurvy.

Nothing noteworthy occurs today.

Dr. informs me that he has requested of Lt. Greely that I accompany him North. Dog
driving is now something that I must give more attention than ever as the event may
occur when the accomplishment will be something more than ornamental.


## Sunday February 19th 1882

Our usual Sunday. The first step towards active field work was the departure of Lt.
Lockwood, Brainard, Frederick and dog team (8) for Beechy. A cold trip it must
prove to be.

Dr. Pavy and I take a walk to Dutch Island. —see private journal—
I find that I have overworked my eyes: have read too much. I must discontinue for a
time. It is however difficult to keep from reading during these cold dark days when
there is little else to do. I presume I have read at least six hours per day all winter.

## Monday February 20th 1882

A very cool morning. The light is increasing so that I thought I would try my
luck with a shotgun today. Whistler and I started for Watercourse Bay. In the ravine
leading to the coal mine we startled up a fine large hare which I followed for miles,
succeeded in getting within about 75 yards of him and risked a shot but without
effect. The strangest part of the affair was the manner in which the little animal
traveled: he stood perfectly upright, kangaroo like, and hopping on his hind legs made
enormous strides. Not until he started to ascend the side of the ravine did he assume
his proper position of a quadruped.

We passed some time at the grotto mentioned by Mr. Hodson in his interesting
article that appeared in the “Frasier’s” after the return of the British expd’n in 1876. It
came fully up to our expectations.

On our return we again startled our hare and I persistently followed it by the
failing light until it disappeared entirely. It began to snow slightly as we came
through the gap and it was difficult to prevent faces from freezing. Whistler’s face was frozen
repeatedly and it took some time to remove the frost—J. R. Lt G —see private
journal—

My eyes still trouble me.

## Tuesday February 21st 1882

I hauled ice as usual. Two of our pups have died. Schneider disconsolate.
Weather still keeps very cold. We are making preparations for the celebration of
Washington’s Birthday tomorrow. I found my weight still holds good—175 lbs.


## Wednesday February 22nd 1882

The patriotic Americans among us have some opportunity of expressing loyal
sentiments today. Lt. Greely in honor of the day arranged to have it spent as a
holiday. An especially palatable dinner was prepared and to diversify the eating
exercise we had a shooting match and snow shoe race.

Lt. Greely favored us with a lecture of the “Father of Our Country”. See
private journal.

Lt. Lockwood and Brainard return from Beechy. They were engaged in extending the
dimensions of the snowhouse there so as to make it accommodate the large parties
that will rendezvous there during the spring sledging trips.

The commanding officer called me and I learned some details of the
prospective spring work. --see private journal this date.
